#!/usr/bin/env bash
# frp all-in-one installer/manager for Linux
# Supports frp v0.52+ TOML config, systemd, frps/frpc, proxy wizard.

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_VERSION="${SCRIPT_VERSION:-2026.05.27-r3}"
FRP_REPO="${FRP_REPO:-fatedier/frp}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
CONFIG_DIR="${CONFIG_DIR:-/etc/frp}"
FRPC_CONF_DIR="${FRPC_CONF_DIR:-${CONFIG_DIR}/frpc.d}"
FRPC_CLIENTS_DIR="${FRPC_CLIENTS_DIR:-${CONFIG_DIR}/clients}"
PRESET_DIR="${PRESET_DIR:-${CONFIG_DIR}/presets.d}"
LOG_DIR="${LOG_DIR:-/var/log/frp}"
TOKEN_FILE="${TOKEN_FILE:-${CONFIG_DIR}/token}"
FRPS_CONFIG="${FRPS_CONFIG:-${CONFIG_DIR}/frps.toml}"
FRPC_CONFIG="${FRPC_CONFIG:-${CONFIG_DIR}/frpc.toml}"
FRPC_STORE="${FRPC_STORE:-${CONFIG_DIR}/frpc-store.json}"
INSTALLER_CONFIG="${INSTALLER_CONFIG:-${CONFIG_DIR}/installer.env}"
INSTALLER_LOG="${INSTALLER_LOG:-${LOG_DIR}/installer.log}"
FRP_USER="${FRP_USER:-frp}"
GH_API="${GH_API:-https://api.github.com/repos/${FRP_REPO}/releases/latest}"
GH_RELEASE_BASE="${GH_RELEASE_BASE:-https://github.com/${FRP_REPO}/releases/download}"
GH_PROXY="${GH_PROXY:-}"

# ---------- colors ----------
if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_BLUE=$'\033[34m'; C_BOLD=$'\033[1m'
else
  C_RESET=''; C_RED=''; C_GREEN=''; C_YELLOW=''; C_BLUE=''; C_BOLD=''
fi

log_event() {
  local level="$1" msg="$2" ts
  ts="$(date '+%F %T %z' 2>/dev/null || printf 'unknown-time')"
  { mkdir -p "$LOG_DIR" && printf '%s [%s] %s\n' "$ts" "$level" "$msg" >> "$INSTALLER_LOG"; } 2>/dev/null || true
}

info() { log_event "INFO" "$*"; printf '%s[INFO]%s %s\n' "$C_BLUE" "$C_RESET" "$*" >&2; }
ok() { log_event "OK" "$*"; printf '%s[OK]%s %s\n' "$C_GREEN" "$C_RESET" "$*" >&2; }
warn() { log_event "WARN" "$*"; printf '%s[WARN]%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
err() { log_event "ERR" "$*"; printf '%s[ERR]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; }
fatal() { err "$*"; exit 1; }

trap 'err "脚本在第 ${LINENO} 行失败，命令：${BASH_COMMAND}"' ERR
trap 'printf "\n" >&2; err "已中断。"; exit 130' INT

# ---------- helpers ----------
need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    fatal "请使用 root 运行：sudo bash $0"
  fi
}

has_cmd() { command -v "$1" >/dev/null 2>&1; }

pause() { read -r -p "按回车继续..." _ || true; }

trim() {
  local s="$*"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

ask() {
  local prompt="$1" default="${2:-}" ans
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " ans || true
    printf '%s' "${ans:-$default}"
  else
    read -r -p "$prompt: " ans || true
    printf '%s' "$ans"
  fi
}

ask_required() {
  local prompt="$1" default="${2:-}" ans
  while true; do
    ans="$(ask "$prompt" "$default")"
    ans="$(trim "$ans")"
    [[ -n "$ans" ]] && { printf '%s' "$ans"; return; }
    warn "不能为空，请重新输入。"
  done
}

confirm() {
  local prompt="$1" default="${2:-Y}" ans hint
  if [[ "$default" =~ ^[Yy]$ ]]; then hint="Y/n"; else hint="y/N"; fi
  read -r -p "$prompt [$hint]: " ans || true
  ans="${ans:-$default}"
  [[ "$ans" =~ ^[Yy]$ ]]
}

ask_port() {
  local prompt="$1" default="${2:-}" port
  while true; do
    port="$(ask "$prompt" "$default")"
    if [[ "$port" =~ ^[0-9]+$ ]] && (( port >= 1 && port <= 65535 )); then
      printf '%s' "$port"; return
    fi
    warn "端口必须是 1-65535 的数字。"
  done
}

ask_yes_no_value() {
  local prompt="$1" default="${2:-n}"
  if confirm "$prompt" "$default"; then printf 'true'; else printf 'false'; fi
}

toml_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

toml_string() { printf '"%s"' "$(toml_escape "$1")"; }

toml_array_from_csv() {
  local csv="$1" item out="" oldifs="$IFS"
  IFS=',' read -r -a arr <<< "$csv"
  IFS="$oldifs"
  for item in "${arr[@]}"; do
    item="$(trim "$item")"
    [[ -z "$item" ]] && continue
    if [[ -n "$out" ]]; then out+=", "; fi
    out+="$(toml_string "$item")"
  done
  printf '[%s]' "$out"
}

normalize_github_proxy() {
  local proxy="${1:-}"
  proxy="$(trim "$proxy")"
  [[ -z "$proxy" ]] && { printf ''; return; }
  proxy="${proxy%/}/"
  printf '%s' "$proxy"
}

apply_github_proxy() {
  local url="$1" proxy
  proxy="$(normalize_github_proxy "${GH_PROXY:-}")"
  if [[ -n "$proxy" ]]; then
    printf '%s%s' "$proxy" "$url"
  else
    printf '%s' "$url"
  fi
}

load_installer_config() {
  # Environment variable has higher priority than saved config.
  [[ -n "${GH_PROXY:-}" ]] && { GH_PROXY="$(normalize_github_proxy "$GH_PROXY")"; return; }
  [[ -f "$INSTALLER_CONFIG" ]] || return 0
  local line value
  line="$(grep -E '^GH_PROXY=' "$INSTALLER_CONFIG" | tail -n1 || true)"
  [[ -n "$line" ]] || return 0
  value="${line#GH_PROXY=}"
  value="$(trim "$value")"
  GH_PROXY="$(normalize_github_proxy "$value")"
}

save_installer_config() {
  mkdir -p "$CONFIG_DIR"
  GH_PROXY="$(normalize_github_proxy "${GH_PROXY:-}")"
  cat > "$INSTALLER_CONFIG" <<EOF_INSTALLER
# Generated by frp manager ${SCRIPT_VERSION}
# GitHub proxy prefix. Empty means direct connection.
# Example: https://ghfast.top/
GH_PROXY=${GH_PROXY}
EOF_INSTALLER
  chmod 640 "$INSTALLER_CONFIG" 2>/dev/null || true
  chown root:"$FRP_USER" "$INSTALLER_CONFIG" 2>/dev/null || chown root:root "$INSTALLER_CONFIG" 2>/dev/null || true
}

configure_github_proxy() {
  load_installer_config
  echo
  info "配置 GitHub 下载代理"
  echo "当前代理：${GH_PROXY:-直连}"
  cat <<'EOF_PROXY_HELP'
说明：这里填写“代理前缀”，脚本会把完整 GitHub URL 拼到后面。
示例：
  https://ghfast.top/
  https://gh-proxy.com/
  https://gh.llkk.cc/
留空则恢复直连。
也可以临时使用环境变量：GH_PROXY=https://ghfast.top/ bash frp.sh
EOF_PROXY_HELP
  local input
  input="$(ask "请输入 GitHub 代理前缀，留空直连" "${GH_PROXY:-}")"
  input="$(trim "$input")"
  if [[ -n "$input" && ! "$input" =~ ^https?:// ]]; then
    warn "代理前缀通常应以 http:// 或 https:// 开头，当前仍按原样保存。"
  fi
  GH_PROXY="$(normalize_github_proxy "$input")"
  save_installer_config
  if [[ -n "$GH_PROXY" ]]; then
    ok "已保存 GitHub 代理：$GH_PROXY"
    echo "测试拼接：$(apply_github_proxy "https://github.com/${FRP_REPO}/releases/download/v0.68.1/frp_0.68.1_linux_amd64.tar.gz")"
  else
    ok "已恢复 GitHub 直连下载。"
  fi
}

random_secret() {
  if has_cmd openssl; then
    openssl rand -base64 32 | tr -d '\n'
  else
    tr -dc 'A-Za-z0-9_=-' </dev/urandom | head -c 43 || true
  fi
}

encrypt_payload_code() {
  local prefix="$1" passphrase="$2" payload="$3" cipher
  has_cmd openssl || fatal "需要 openssl 才能生成加密导入码。"
  [[ -n "$passphrase" ]] || fatal "加密口令不能为空。"
  cipher="$(printf '%s' "$payload" | openssl enc -aes-256-cbc -pbkdf2 -salt -base64 -A -pass "pass:${passphrase}")"
  printf '%s:%s' "$prefix" "$cipher"
}

decrypt_payload_code() {
  local prefix="$1" passphrase="$2" code="$3" cipher
  has_cmd openssl || fatal "需要 openssl 才能解密导入码。"
  [[ -n "$passphrase" ]] || fatal "解密口令不能为空。"
  case "$code" in
    "${prefix}:"*) cipher="${code#${prefix}:}" ;;
    *) fatal "导入码前缀不正确，期望 ${prefix}:..." ;;
  esac
  printf '%s' "$cipher" | openssl enc -aes-256-cbc -pbkdf2 -d -base64 -A -pass "pass:${passphrase}"
}

parse_payload_value() {
  local payload="$1" key="$2"
  awk -v want="$key" '
    function trim(s) {
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
      return s
    }
    {
      line=$0
      pos=index(line, "=")
      if (pos == 0) next
      k=trim(substr(line, 1, pos-1))
      v=trim(substr(line, pos+1))
      if (k == want) {
        if (v ~ /^".*"$/) {
          sub(/^"/, "", v)
          sub(/"$/, "", v)
          gsub(/\\"/, "\"", v)
          gsub(/\\\\/, "\\", v)
        }
        print v
        exit
      }
    }
  ' <<< "$payload"
}

read_toml_value() {
  local file="$1" key="$2"
  [[ -f "$file" ]] || return 0
  awk -v want="$key" '
    function trim(s) {
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
      return s
    }
    {
      line=$0
      pos=index(line, "=")
      if (pos == 0) next
      k=trim(substr(line, 1, pos-1))
      v=trim(substr(line, pos+1))
      if (k == want) {
        if (v ~ /^".*"$/) {
          sub(/^"/, "", v)
          sub(/"$/, "", v)
        }
        print v
        exit
      }
    }
  ' "$file"
}

write_token_file() {
  local file="$1" token="$2" dir
  dir="${file%/*}"
  mkdir -p "$dir"
  printf '%s\n' "$token" > "$file"
  chown root:"$FRP_USER" "$file" 2>/dev/null || chown root:root "$file" 2>/dev/null || true
  chmod 640 "$file" 2>/dev/null || true
}

print_banner() {
  clear 2>/dev/null || true
  printf '%sfrp 管理脚本 %s%s\n' "$C_BOLD" "$SCRIPT_VERSION" "$C_RESET"
  render_status_bar
  echo
}

install_dependencies() {
  local missing=() c
  for c in curl tar gzip grep sed awk uname chmod chown mkdir rm cp mv; do
    has_cmd "$c" || missing+=("$c")
  done
  # openssl is optional but useful for random token.
  has_cmd openssl || missing+=("openssl")

  if (( ${#missing[@]} == 0 )); then
    return
  fi

  warn "缺少依赖：${missing[*]}"
  if ! confirm "是否自动安装依赖" "Y"; then
    fatal "缺少依赖，无法继续。"
  fi

  if has_cmd apt-get; then
    apt-get update
    apt-get install -y curl tar gzip grep sed gawk coreutils openssl ca-certificates
  elif has_cmd dnf; then
    dnf install -y curl tar gzip grep sed gawk coreutils openssl ca-certificates
  elif has_cmd yum; then
    yum install -y curl tar gzip grep sed gawk coreutils openssl ca-certificates
  elif has_cmd apk; then
    apk add --no-cache curl tar gzip grep sed gawk coreutils openssl ca-certificates
  elif has_cmd pacman; then
    pacman -Sy --noconfirm curl tar gzip grep sed gawk coreutils openssl ca-certificates
  else
    fatal "未识别包管理器，请手动安装：${missing[*]}"
  fi
}

detect_arch() {
  local arch
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    armv7l|armv7*) echo "arm" ;;
    armv6l|armv6*) echo "arm" ;;
    i386|i686) echo "386" ;;
    *) fatal "暂不支持架构：$arch" ;;
  esac
}

fetch_latest_version_tag() {
  load_installer_config
  local tag json api_url
  api_url="$(apply_github_proxy "$GH_API")"
  json="$(curl -fsSL --connect-timeout 15 --retry 2 --retry-delay 1 "$api_url" 2>/dev/null || true)"
  if [[ -z "$json" && -n "${GH_PROXY:-}" ]]; then
    warn "通过 GitHub 代理获取 latest 失败，尝试直连 api.github.com。"
    json="$(curl -fsSL --connect-timeout 15 --retry 2 --retry-delay 1 "$GH_API" 2>/dev/null || true)"
  fi
  tag="$(printf '%s' "$json" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\(v[0-9][^"]*\)".*/\1/p' | head -n1)"
  [[ -n "$tag" ]] || return 1
  printf '%s' "$tag"
}

get_latest_version() {
  local tag
  tag="$(fetch_latest_version_tag || true)"
  [[ -n "$tag" ]] || fatal "获取 frp 最新版本失败，可以手动输入版本，例如 v0.68.1，或先配置 GitHub 代理。"
  printf '%s' "$tag"
}

normalize_version_tag() {
  local text="${1:-}" version
  version="$(printf '%s' "$text" | grep -Eo 'v?[0-9]+([.][0-9]+){1,3}([-+._A-Za-z0-9]*)?' | head -n1 || true)"
  [[ -n "$version" ]] || return 1
  [[ "$version" =~ ^v ]] || version="v${version}"
  printf '%s' "$version"
}

resolve_default_version() {
  local explicit="${1:-}" installed="${2:-}" latest="${3:-}" default_version
  if [[ -n "$explicit" ]]; then
    default_version="$explicit"
  elif [[ -n "$latest" ]]; then
    default_version="$latest"
  else
    default_version="$installed"
  fi
  [[ -n "$default_version" ]] || return 1
  normalize_version_tag "$default_version"
}

select_version() {
  local default_version version installed_version latest_version
  installed_version="$(installed_frp_version)"
  if [[ -n "$installed_version" ]]; then
    info "检测到本机已安装 frp：${installed_version}"
  fi

  if [[ -z "${VERSION:-}" ]]; then
    info "正在获取 frp 最新版本..."
    latest_version="$(fetch_latest_version_tag || true)"
    if [[ -z "$latest_version" && -n "$installed_version" ]]; then
      warn "获取最新版本失败，将默认使用本机已安装版本 ${installed_version}。"
    elif [[ -z "$latest_version" ]]; then
      fatal "获取 frp 最新版本失败，可以手动输入 VERSION=v0.68.1，或先配置 GitHub 代理。"
    fi
  fi

  default_version="$(resolve_default_version "${VERSION:-}" "$installed_version" "$latest_version")"
  version="$(ask "请输入 frp 版本，保留默认；当前已安装 ${installed_version:-无}" "$default_version")"
  [[ "$version" =~ ^v ]] || version="v${version}"
  printf '%s' "$version"
}

binary_version_tag() {
  local bin="$1" text
  [[ -x "$bin" ]] || return 1
  text="$(frp_version_text "$bin")"
  normalize_version_tag "$text"
}

installed_frp_version() {
  local frps_version="" frpc_version=""
  frps_version="$(binary_version_tag "${INSTALL_DIR}/frps" 2>/dev/null || true)"
  frpc_version="$(binary_version_tag "${INSTALL_DIR}/frpc" 2>/dev/null || true)"

  if [[ -n "$frps_version" && "$frps_version" == "$frpc_version" ]]; then
    printf '%s' "$frps_version"
  elif [[ -n "$frps_version" && -n "$frpc_version" ]]; then
    printf 'frps %s / frpc %s' "$frps_version" "$frpc_version"
  else
    printf '%s' "${frps_version:-$frpc_version}"
  fi
}

should_skip_frp_download() {
  local target_version="$1" reinstall_answer="${2:-}" frps_version="" frpc_version="" installed_version
  target_version="$(normalize_version_tag "$target_version")"
  frps_version="$(binary_version_tag "${INSTALL_DIR}/frps" 2>/dev/null || true)"
  frpc_version="$(binary_version_tag "${INSTALL_DIR}/frpc" 2>/dev/null || true)"
  [[ -n "$frps_version" && -n "$frpc_version" ]] || return 1
  [[ "$frps_version" == "$frpc_version" && "$frps_version" == "$target_version" ]] || return 1
  installed_version="$frps_version"

  if [[ -n "$reinstall_answer" ]]; then
    [[ "$reinstall_answer" =~ ^[Nn]$ ]]
    return
  fi

  warn "检测到本机已安装 frp ${installed_version}，与目标版本相同。"
  if confirm "是否仍然重新下载并覆盖安装" "n"; then
    return 1
  fi
  ok "已跳过二进制下载，继续使用本机 frp ${installed_version}。"
  return 0
}

create_dirs_and_user() {
  mkdir -p "$CONFIG_DIR" "$FRPC_CONF_DIR" "$FRPC_CLIENTS_DIR" "$PRESET_DIR" "$LOG_DIR"

  if ! id "$FRP_USER" >/dev/null 2>&1; then
    if has_cmd useradd; then
      useradd --system --no-create-home --shell /usr/sbin/nologin "$FRP_USER" 2>/dev/null || \
      useradd --system --no-create-home --shell /bin/false "$FRP_USER"
    elif has_cmd adduser; then
      adduser -S -D -H -s /sbin/nologin "$FRP_USER" 2>/dev/null || true
    fi
  fi

  if id "$FRP_USER" >/dev/null 2>&1; then
    chown -R root:"$FRP_USER" "$CONFIG_DIR"
    chown -R "$FRP_USER":"$FRP_USER" "$LOG_DIR"
    chmod 750 "$CONFIG_DIR" "$FRPC_CONF_DIR" "$FRPC_CLIENTS_DIR" "$PRESET_DIR"
  else
    warn "无法创建系统用户 $FRP_USER，将使用 root 运行 systemd 服务。"
  fi
}

download_and_install_frp() {
  load_installer_config
  local version="$1" arch url direct_url tmpdir archive dirname
  arch="$(detect_arch)"
  archive="frp_${version#v}_linux_${arch}.tar.gz"
  direct_url="${GH_RELEASE_BASE}/${version}/${archive}"
  url="$(apply_github_proxy "$direct_url")"

  tmpdir="$(mktemp -d)"
  info "下载：$url"
  if ! curl -fL --connect-timeout 15 --retry 3 --retry-delay 2 -o "${tmpdir}/${archive}" "$url"; then
    if [[ -n "${GH_PROXY:-}" ]]; then
      warn "通过 GitHub 代理下载失败，尝试直连 GitHub。"
      info "下载：$direct_url"
      curl -fL --connect-timeout 15 --retry 3 --retry-delay 2 -o "${tmpdir}/${archive}" "$direct_url"
    else
      return 1
    fi
  fi
  tar -xzf "${tmpdir}/${archive}" -C "$tmpdir"
  dirname="${tmpdir}/frp_${version#v}_linux_${arch}"
  [[ -x "${dirname}/frps" && -x "${dirname}/frpc" ]] || fatal "压缩包中没有找到 frps/frpc。"

  install -m 0755 "${dirname}/frps" "${INSTALL_DIR}/frps"
  install -m 0755 "${dirname}/frpc" "${INSTALL_DIR}/frpc"
  rm -rf "$tmpdir"

  ok "frp ${version} 已安装到 ${INSTALL_DIR}"
  printf "frps: %s\n" "$(frp_version_text "${INSTALL_DIR}/frps")"
}

ensure_token_file() {
  local token="${1:-}"
  if [[ -z "$token" ]]; then
    if [[ -s "$TOKEN_FILE" ]]; then
      token="$(tr -d '[:space:]' < "$TOKEN_FILE")"
    else
      token="$(random_secret)"
    fi
  fi
  write_token_file "$TOKEN_FILE" "$token"
}

write_systemd_service() {
  local name="$1" bin="$2" conf="$3" extra_args="${4:-}" user_line group_line cap_line
  if id "$FRP_USER" >/dev/null 2>&1; then
    user_line="User=${FRP_USER}"
    group_line="Group=${FRP_USER}"
  else
    user_line=""
    group_line=""
  fi

  # Allows binding low ports such as 80/443 when running as non-root.
  cap_line=$'AmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE'

  cat > "/etc/systemd/system/${name}.service" <<EOF_SERVICE
[Unit]
Description=frp ${name#frp} service
Documentation=https://gofrp.org/zh-cn/docs/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
${user_line}
${group_line}
ExecStart=${bin} -c ${conf}${extra_args:+ ${extra_args}}
Restart=on-failure
RestartSec=5s
LimitNOFILE=1048576
${cap_line}
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=${CONFIG_DIR} ${LOG_DIR}

[Install]
WantedBy=multi-user.target
EOF_SERVICE

  systemctl daemon-reload
  ok "已写入 /etc/systemd/system/${name}.service"
}

systemctl_enable_restart() {
  local service="$1"
  systemctl enable "$service" >/dev/null
  systemctl restart "$service"
  ok "${service} 已启动并设置开机自启。"
  systemctl --no-pager --full status "$service" || true
}

try_open_firewall_port() {
  local port="$1" proto="${2:-tcp}"
  [[ -z "$port" ]] && return 0
  if has_cmd ufw && ufw status 2>/dev/null | grep -qi '^Status: active'; then
    if confirm "检测到 UFW，是否放行 ${port}/${proto}" "Y"; then
      ufw allow "${port}/${proto}" || true
    fi
  elif has_cmd firewall-cmd && firewall-cmd --state >/dev/null 2>&1; then
    if confirm "检测到 firewalld，是否放行 ${port}/${proto}" "Y"; then
      firewall-cmd --permanent --add-port="${port}/${proto}" || true
      firewall-cmd --reload || true
    fi
  fi
}

verify_config() {
  local bin="$1" conf="$2"
  if [[ -x "$bin" && -f "$conf" ]]; then
    info "校验配置：$bin verify -c $conf"
    "$bin" verify -c "$conf"
  fi
}

frp_version_text() {
  local bin="$1" out=""
  [[ -x "$bin" ]] || return 0
  out="$("$bin" version 2>/dev/null || true)"
  [[ -n "$out" ]] || out="$("$bin" -v 2>/dev/null || true)"
  [[ -n "$out" ]] || out="$("$bin" --version 2>/dev/null || true)"
  printf '%s' "$out"
}

service_status_label() {
  local service="$1" active="" enabled=""
  has_cmd systemctl || { printf '服务状态未知'; return 0; }
  if ! systemctl list-unit-files "${service}.service" >/dev/null 2>&1; then
    printf '未装服务'
    return 0
  fi
  active="$(systemctl is-active "$service" 2>/dev/null || true)"
  enabled="$(systemctl is-enabled "$service" 2>/dev/null || true)"
  [[ -n "$active" ]] || active="unknown"
  [[ -n "$enabled" ]] || enabled="unknown"
  case "$active" in
    active) active="运行" ;;
    inactive) active="停止" ;;
    failed) active="失败" ;;
    *) active="未知" ;;
  esac
  case "$enabled" in
    enabled) enabled="自启" ;;
    disabled) enabled="未自启" ;;
    static) enabled="静态" ;;
    *) enabled="未知" ;;
  esac
  printf '%s/%s' "$active" "$enabled"
}

config_status_label() {
  local conf="$1"
  if [[ -s "$conf" ]]; then
    printf '已配置'
  elif [[ -f "$conf" ]]; then
    printf '空配置'
  else
    printf '未配置'
  fi
}

render_component_status() {
  local name="$1" bin="$2" conf="$3" service="$4" version config_state service_state
  version="$(binary_version_tag "$bin" 2>/dev/null || true)"
  [[ -n "$version" ]] || version="未安装"
  config_state="$(config_status_label "$conf")"
  service_state="$(service_status_label "$service")"
  printf '%s: %s/%s/%s' "$name" "$version" "$config_state" "$service_state"
}

service_brief_label() {
  local service="$1" active=""
  if ! has_cmd systemctl || ! systemctl list-unit-files "${service}.service" >/dev/null 2>&1; then
    printf '未运行'
    return 0
  fi
  active="$(systemctl is-active "$service" 2>/dev/null || true)"
  case "$active" in
    active) printf '运行中' ;;
    failed) printf '异常' ;;
    *) printf '未运行' ;;
  esac
}

render_status_bar() {
  local instance_count
  instance_count="$(list_frpc_instances 2>/dev/null | wc -l | tr -d '[:space:]')"
  printf '状态：服务端:%s | 客户端:%s | 实例:%s\n' \
    "$(service_brief_label frps)" \
    "$(service_brief_label frpc)" \
    "$instance_count"
}

validate_instance_name() {
  local name="${1:-}"
  [[ "$name" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$ ]] || return 1
  [[ "$name" != "." && "$name" != ".." ]]
}

instance_dir() {
  local name="$1"
  validate_instance_name "$name" || return 1
  printf '%s/%s' "$FRPC_CLIENTS_DIR" "$name"
}

instance_frpc_config() {
  printf '%s/frpc.toml' "$(instance_dir "$1")"
}

instance_frpc_conf_dir() {
  printf '%s/frpc.d' "$(instance_dir "$1")"
}

instance_token_file() {
  printf '%s/token' "$(instance_dir "$1")"
}

instance_log_file() {
  local name="$1"
  validate_instance_name "$name" || return 1
  printf '%s/frpc-%s.log' "$LOG_DIR" "$name"
}

instance_service_name() {
  local name="$1"
  validate_instance_name "$name" || return 1
  printf 'frpc@%s' "$name"
}

write_frpc_base_config() {
  local config="$1" split_dir="$2" token_file="$3" log_file="$4"
  local server_addr="$5" server_port="$6" user_name="$7" proto="$8"
  local tls_enable="$9" pool_count="${10}" dns_server="${11}"
  local admin_addr="${12}" admin_port="${13}" admin_user="${14}" admin_pass="${15}"
  local store_path="${16}" enable_store="${17}" config_dir

  config_dir="${config%/*}"
  mkdir -p "$config_dir" "$split_dir" "${log_file%/*}"

  cat > "$config" <<EOF_FRPC_BASE
# Generated by frp manager ${SCRIPT_VERSION}
serverAddr = "$(toml_escape "$server_addr")"
serverPort = ${server_port}
loginFailExit = true
includes = ["$(toml_escape "$split_dir")/*.toml"]

# Token authentication. The token is stored outside this config file.
auth.method = "token"
auth.tokenSource.type = "file"
auth.tokenSource.file.path = "$(toml_escape "$token_file")"

# Transport.
transport.protocol = "$(toml_escape "$proto")"
transport.tls.enable = ${tls_enable}
transport.poolCount = ${pool_count}

# Logs.
log.to = "$(toml_escape "$log_file")"
log.level = "info"
log.maxDays = 7
log.disablePrintColor = true
EOF_FRPC_BASE

  [[ -n "$user_name" ]] && echo "user = \"$(toml_escape "$user_name")\"" >> "$config"
  [[ -n "$dns_server" ]] && echo "dnsServer = \"$(toml_escape "$dns_server")\"" >> "$config"

  if [[ -n "$admin_addr" && -n "$admin_port" ]]; then
    cat >> "$config" <<EOF_FRPC_ADMIN

# Admin UI / runtime proxy management.
webServer.addr = "$(toml_escape "$admin_addr")"
webServer.port = ${admin_port}
webServer.user = "$(toml_escape "$admin_user")"
webServer.password = "$(toml_escape "$admin_pass")"
EOF_FRPC_ADMIN
    if [[ "$enable_store" == "true" ]]; then
      cat >> "$config" <<EOF_FRPC_STORE

[store]
path = "$(toml_escape "$store_path")"
EOF_FRPC_STORE
    fi
  fi

  chown root:"$FRP_USER" "$config" 2>/dev/null || true
  chmod 640 "$config" 2>/dev/null || true
}

render_frpc_pairing_payload() {
  local server_addr="$1" server_port="$2" token="$3" proto="$4"
  local tls_enable="$5" pool_count="$6" dns_server="$7" user_name="$8"
  cat <<EOF_FRPC_PAIRING
format = "install-frp-frpc-v1"
serverAddr = "$(toml_escape "$server_addr")"
serverPort = ${server_port}
token = "$(toml_escape "$token")"
transportProtocol = "$(toml_escape "$proto")"
tlsEnable = ${tls_enable}
poolCount = ${pool_count}
dnsServer = "$(toml_escape "$dns_server")"
userName = "$(toml_escape "$user_name")"
EOF_FRPC_PAIRING
}

write_frpc_config_from_pairing_payload() {
  local config="$1" split_dir="$2" token_file="$3" log_file="$4" store_file="$5" payload="$6"
  local format server_addr server_port token proto tls_enable pool_count dns_server user_name
  format="$(parse_payload_value "$payload" format)"
  [[ "$format" == "install-frp-frpc-v1" ]] || fatal "frps 配对码内容格式不正确。"
  server_addr="$(parse_payload_value "$payload" serverAddr)"
  server_port="$(parse_payload_value "$payload" serverPort)"
  token="$(parse_payload_value "$payload" token)"
  proto="$(parse_payload_value "$payload" transportProtocol)"
  tls_enable="$(parse_payload_value "$payload" tlsEnable)"
  pool_count="$(parse_payload_value "$payload" poolCount)"
  dns_server="$(parse_payload_value "$payload" dnsServer)"
  user_name="$(parse_payload_value "$payload" userName)"
  [[ -n "$server_addr" && -n "$server_port" && -n "$token" ]] || fatal "frps 配对码缺少 serverAddr/serverPort/token。"
  [[ -n "$proto" ]] || proto="tcp"
  [[ -n "$tls_enable" ]] || tls_enable="true"
  [[ -n "$pool_count" ]] || pool_count="0"

  write_token_file "$token_file" "$token"
  write_frpc_base_config \
    "$config" \
    "$split_dir" \
    "$token_file" \
    "$log_file" \
    "$server_addr" \
    "$server_port" \
    "$user_name" \
    "$proto" \
    "$tls_enable" \
    "$pool_count" \
    "$dns_server" \
    "" \
    "" \
    "" \
    "" \
    "$store_file" \
    "false"
}

list_frpc_instances() {
  local file
  [[ -d "$FRPC_CLIENTS_DIR" ]] || return 0
  while IFS= read -r -d '' file; do
    basename "$(dirname "$file")"
  done < <(find "$FRPC_CLIENTS_DIR" -mindepth 2 -maxdepth 2 -type f -name frpc.toml -print0 2>/dev/null | sort -z)
}

render_frpc_template_service() {
  local user_line="" group_line="" cap_line
  if id "$FRP_USER" >/dev/null 2>&1; then
    user_line="User=${FRP_USER}"
    group_line="Group=${FRP_USER}"
  fi
  cap_line=$'AmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE'

  cat <<EOF_SERVICE
[Unit]
Description=frp client instance %i service
Documentation=https://gofrp.org/zh-cn/docs/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
${user_line}
${group_line}
ExecStart=${INSTALL_DIR}/frpc -c ${FRPC_CLIENTS_DIR}/%i/frpc.toml
Restart=on-failure
RestartSec=5s
LimitNOFILE=1048576
${cap_line}
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=${FRPC_CLIENTS_DIR}/%i ${LOG_DIR}

[Install]
WantedBy=multi-user.target
EOF_SERVICE
}

write_frpc_template_service() {
  render_frpc_template_service > /etc/systemd/system/frpc@.service
  systemctl daemon-reload
  ok "已写入 /etc/systemd/system/frpc@.service"
}

configure_named_frpc_instance() {
  create_dirs_and_user
  local name dir config split_dir token_file log_file store_file
  local server_addr server_port token user_name proto tls_enable pool_count dns_server
  local enable_admin admin_addr admin_port admin_user admin_pass enable_store service

  echo
  info "配置命名 frpc 客户端实例"
  while true; do
    name="$(ask_required "实例名，只能使用字母数字点号下划线短横线，例如 home" "")"
    if validate_instance_name "$name"; then
      break
    fi
    warn "实例名不合法，请使用 1-63 位字母、数字、点号、下划线或短横线，且以字母或数字开头。"
  done

  dir="$(instance_dir "$name")"
  config="$(instance_frpc_config "$name")"
  split_dir="$(instance_frpc_conf_dir "$name")"
  token_file="$(instance_token_file "$name")"
  log_file="$(instance_log_file "$name")"
  store_file="${dir}/frpc-store.json"
  mkdir -p "$dir" "$split_dir"

  server_addr="$(ask_required "frps 服务器地址 serverAddr/IP/域名" "")"
  server_port="$(ask_port "frps 服务器端口 serverPort" "7000")"
  token="$(ask "鉴权 token，留空自动生成/沿用 ${token_file}" "")"
  if [[ -z "$token" && -s "$token_file" ]]; then
    token="$(tr -d '[:space:]' < "$token_file")"
  fi
  [[ -z "$token" ]] && token="$(random_secret)"
  write_token_file "$token_file" "$token"
  user_name="$(ask "客户端 user，留空不设置；多人共用服务端建议填写" "")"

  echo "通信协议可选：tcp / kcp / quic / websocket / wss"
  proto="$(ask "transport.protocol" "tcp")"
  case "$proto" in tcp|kcp|quic|websocket|wss) ;; *) warn "未知协议，回退 tcp"; proto="tcp" ;; esac
  tls_enable="$(ask_yes_no_value "是否启用 frpc->frps TLS；新版默认启用，建议保留" "Y")"
  pool_count="$(ask "连接池数量 transport.poolCount，普通场景 0，短连接高并发可 1-5" "0")"
  [[ "$pool_count" =~ ^[0-9]+$ ]] || pool_count=0
  dns_server="$(ask "自定义 DNS 服务器，留空使用系统 DNS，例如 1.1.1.1" "")"

  enable_admin="$(ask_yes_no_value "是否启用该实例的 Admin UI / 动态代理管理" "n")"
  if [[ "$enable_admin" == "true" ]]; then
    admin_addr="$(ask "Admin UI 监听地址，建议 127.0.0.1" "127.0.0.1")"
    admin_port="$(ask_port "Admin UI 端口" "7400")"
    admin_user="$(ask "Admin UI 用户名" "admin")"
    admin_pass="$(ask "Admin UI 密码，留空随机生成" "")"
    [[ -z "$admin_pass" ]] && admin_pass="$(random_secret | cut -c1-16)"
    enable_store="$(ask_yes_no_value "是否启用 Store 动态代理持久化" "Y")"
  else
    admin_addr=""; admin_port=""; admin_user=""; admin_pass=""; enable_store="false"
  fi

  if [[ -f "$config" ]]; then
    cp -a "$config" "${config}.bak.$(date +%Y%m%d-%H%M%S)"
  fi

  write_frpc_base_config \
    "$config" \
    "$split_dir" \
    "$token_file" \
    "$log_file" \
    "$server_addr" \
    "$server_port" \
    "$user_name" \
    "$proto" \
    "$tls_enable" \
    "$pool_count" \
    "$dns_server" \
    "$admin_addr" \
    "$admin_port" \
    "$admin_user" \
    "$admin_pass" \
    "$store_file" \
    "$enable_store"

  verify_config "${INSTALL_DIR}/frpc" "$config"
  write_frpc_template_service
  service="$(instance_service_name "$name")"
  if confirm "是否现在启动/重启 ${service}" "Y"; then
    systemctl_enable_restart "$service"
  fi

  echo
  ok "frpc 实例 ${name} 配置完成：$config"
  echo "代理拆分配置目录：$split_dir"
}

# ---------- frps ----------
install_or_update_binaries() {
  install_dependencies
  create_dirs_and_user
  local version
  version="$(select_version)"
  if should_skip_frp_download "$version"; then
    return 0
  fi
  download_and_install_frp "$version"
}

configure_frps() {
  create_dirs_and_user
  local bind_addr bind_port token token_value enable_kcp enable_quic kcp_port quic_port
  local enable_http http_port enable_https https_port subdomain_host
  local enable_dashboard dash_addr dash_port dash_user dash_pass enable_prom max_pool

  echo
  info "配置 frps 服务端"
  bind_addr="$(ask "frps 监听地址" "0.0.0.0")"
  bind_port="$(ask_port "frps 主通信端口 bindPort" "7000")"
  token="$(ask "鉴权 token，留空自动生成/沿用" "")"
  ensure_token_file "$token"
  token_value="$(tr -d '[:space:]' < "$TOKEN_FILE")"

  enable_kcp="$(ask_yes_no_value "是否启用 KCP UDP 通信端口" "n")"
  if [[ "$enable_kcp" == "true" ]]; then
    kcp_port="$(ask_port "KCP UDP 端口 kcpBindPort" "$bind_port")"
  else
    kcp_port=""
  fi

  enable_quic="$(ask_yes_no_value "是否启用 QUIC UDP 通信端口" "n")"
  if [[ "$enable_quic" == "true" ]]; then
    quic_port="$(ask_port "QUIC UDP 端口 quicBindPort" "$bind_port")"
  else
    quic_port=""
  fi

  enable_http="$(ask_yes_no_value "是否启用 HTTP 虚拟主机代理" "n")"
  if [[ "$enable_http" == "true" ]]; then
    http_port="$(ask_port "HTTP 访问端口 vhostHTTPPort" "80")"
  else
    http_port=""
  fi

  enable_https="$(ask_yes_no_value "是否启用 HTTPS 虚拟主机代理" "n")"
  if [[ "$enable_https" == "true" ]]; then
    https_port="$(ask_port "HTTPS 访问端口 vhostHTTPSPort" "443")"
  else
    https_port=""
  fi

  subdomain_host="$(ask "泛域名后缀 subDomainHost，留空跳过，例如 frp.example.com" "")"

  enable_dashboard="$(ask_yes_no_value "是否启用 frps Dashboard / Prometheus" "Y")"
  if [[ "$enable_dashboard" == "true" ]]; then
    dash_addr="$(ask "Dashboard 监听地址，公网访问用 0.0.0.0，本机安全用 127.0.0.1" "0.0.0.0")"
    dash_port="$(ask_port "Dashboard 端口" "7500")"
    dash_user="$(ask "Dashboard 用户名" "admin")"
    dash_pass="$(ask "Dashboard 密码，留空随机生成" "")"
    [[ -z "$dash_pass" ]] && dash_pass="$(random_secret | cut -c1-16)"
    enable_prom="$(ask_yes_no_value "是否启用 Prometheus 指标" "Y")"
  else
    dash_addr=""; dash_port=""; dash_user=""; dash_pass=""; enable_prom="false"
  fi

  max_pool="$(ask_port "服务端允许的最大连接池数量 transport.maxPoolCount" "5")"

  if [[ -f "$FRPS_CONFIG" ]]; then
    cp -a "$FRPS_CONFIG" "${FRPS_CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"
  fi

  cat > "$FRPS_CONFIG" <<EOF_FRPS
# Generated by frp manager ${SCRIPT_VERSION}
bindAddr = "$(toml_escape "$bind_addr")"
bindPort = ${bind_port}

# Token authentication.
auth.method = "token"
auth.token = "$(toml_escape "$token_value")"

# Transport tuning.
transport.maxPoolCount = ${max_pool}

# Logs.
log.to = "${LOG_DIR}/frps.log"
log.level = "info"
log.maxDays = 7
log.disablePrintColor = true
EOF_FRPS

  [[ -n "$kcp_port" ]] && echo "kcpBindPort = ${kcp_port}" >> "$FRPS_CONFIG"
  [[ -n "$quic_port" ]] && echo "quicBindPort = ${quic_port}" >> "$FRPS_CONFIG"
  [[ -n "$http_port" ]] && echo "vhostHTTPPort = ${http_port}" >> "$FRPS_CONFIG"
  [[ -n "$https_port" ]] && echo "vhostHTTPSPort = ${https_port}" >> "$FRPS_CONFIG"
  [[ -n "$subdomain_host" ]] && echo "subDomainHost = \"$(toml_escape "$subdomain_host")\"" >> "$FRPS_CONFIG"

  if [[ "$enable_dashboard" == "true" ]]; then
    cat >> "$FRPS_CONFIG" <<EOF_FRPS_DASH

# Dashboard / API / Prometheus.
webServer.addr = "$(toml_escape "$dash_addr")"
webServer.port = ${dash_port}
webServer.user = "$(toml_escape "$dash_user")"
webServer.password = "$(toml_escape "$dash_pass")"
enablePrometheus = ${enable_prom}
EOF_FRPS_DASH
  fi

  chown root:"$FRP_USER" "$FRPS_CONFIG" 2>/dev/null || true
  chmod 640 "$FRPS_CONFIG"
  verify_config "${INSTALL_DIR}/frps" "$FRPS_CONFIG"

  write_systemd_service "frps" "${INSTALL_DIR}/frps" "$FRPS_CONFIG"
  if confirm "是否现在启动/重启 frps" "Y"; then
    systemctl_enable_restart frps
  fi

  try_open_firewall_port "$bind_port" "tcp"
  [[ -n "$kcp_port" ]] && try_open_firewall_port "$kcp_port" "udp"
  [[ -n "$quic_port" ]] && try_open_firewall_port "$quic_port" "udp"
  [[ -n "$http_port" ]] && try_open_firewall_port "$http_port" "tcp"
  [[ -n "$https_port" ]] && try_open_firewall_port "$https_port" "tcp"
  [[ -n "$dash_port" ]] && try_open_firewall_port "$dash_port" "tcp"

  echo
  ok "frps 配置完成：$FRPS_CONFIG"
  echo "Token 文件：$TOKEN_FILE"
  if [[ "$enable_dashboard" == "true" ]]; then
    echo "Dashboard: http://${dash_addr}:${dash_port}  用户：${dash_user}  密码：${dash_pass}"
  fi
}

install_frps_flow() {
  install_or_update_binaries
  configure_frps
}

# ---------- frpc ----------
configure_frpc() {
  create_dirs_and_user
  local server_addr server_port token user_name proto tls_enable pool_count dns_server
  local enable_admin admin_addr admin_port admin_user admin_pass enable_store

  echo
  info "配置 frpc 客户端"
  server_addr="$(ask_required "frps 服务器地址 serverAddr/IP/域名" "")"
  server_port="$(ask_port "frps 服务器端口 serverPort" "7000")"
  token="$(ask "鉴权 token，留空自动生成/沿用 ${TOKEN_FILE}" "")"
  ensure_token_file "$token"
  user_name="$(ask "客户端 user，留空不设置；多人共用服务端建议填写" "")"

  echo "通信协议可选：tcp / kcp / quic / websocket / wss"
  proto="$(ask "transport.protocol" "tcp")"
  case "$proto" in tcp|kcp|quic|websocket|wss) ;; *) warn "未知协议，回退 tcp"; proto="tcp" ;; esac
  tls_enable="$(ask_yes_no_value "是否启用 frpc->frps TLS；新版默认启用，建议保留" "Y")"
  pool_count="$(ask "连接池数量 transport.poolCount，普通场景 0，短连接高并发可 1-5" "0")"
  [[ "$pool_count" =~ ^[0-9]+$ ]] || pool_count=0
  dns_server="$(ask "自定义 DNS 服务器，留空使用系统 DNS，例如 1.1.1.1" "")"

  enable_admin="$(ask_yes_no_value "是否启用 frpc Admin UI / 动态代理管理" "Y")"
  if [[ "$enable_admin" == "true" ]]; then
    admin_addr="$(ask "Admin UI 监听地址，建议 127.0.0.1" "127.0.0.1")"
    admin_port="$(ask_port "Admin UI 端口" "7400")"
    admin_user="$(ask "Admin UI 用户名" "admin")"
    admin_pass="$(ask "Admin UI 密码，留空随机生成" "")"
    [[ -z "$admin_pass" ]] && admin_pass="$(random_secret | cut -c1-16)"
    enable_store="$(ask_yes_no_value "是否启用 Store 动态代理持久化" "Y")"
  else
    admin_addr=""; admin_port=""; admin_user=""; admin_pass=""; enable_store="false"
  fi

  if [[ -f "$FRPC_CONFIG" ]]; then
    cp -a "$FRPC_CONFIG" "${FRPC_CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"
  fi

  write_frpc_base_config \
    "$FRPC_CONFIG" \
    "$FRPC_CONF_DIR" \
    "$TOKEN_FILE" \
    "${LOG_DIR}/frpc.log" \
    "$server_addr" \
    "$server_port" \
    "$user_name" \
    "$proto" \
    "$tls_enable" \
    "$pool_count" \
    "$dns_server" \
    "$admin_addr" \
    "$admin_port" \
    "$admin_user" \
    "$admin_pass" \
    "$FRPC_STORE" \
    "$enable_store"

  chown root:"$FRP_USER" "$FRPC_CONFIG" 2>/dev/null || true
  chmod 640 "$FRPC_CONFIG"
  verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"

  write_systemd_service "frpc" "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"
  if confirm "是否现在启动/重启 frpc" "Y"; then
    systemctl_enable_restart frpc
  fi

  echo
  ok "frpc 主配置完成：$FRPC_CONFIG"
  echo "代理拆分配置目录：$FRPC_CONF_DIR"
  if [[ "$enable_admin" == "true" ]]; then
    echo "Admin UI: http://${admin_addr}:${admin_port}  用户：${admin_user}  密码：${admin_pass}"
  fi
}

install_frpc_flow() {
  install_or_update_binaries
  configure_frpc
}

append_common_proxy_options() {
  local file="$1" type="$2"
  local use_comp bw health hc_type hc_path
  if confirm "是否启用该代理的压缩 transport.useCompression" "n"; then
    echo "transport.useCompression = true" >> "$file"
  fi
  bw="$(ask "限速 bandwidthLimit，留空不限制，例如 10MB 或 512KB" "")"
  if [[ -n "$bw" ]]; then
    echo "transport.bandwidthLimit = \"$(toml_escape "$bw")\"" >> "$file"
    echo "transport.bandwidthLimitMode = \"client\"" >> "$file"
  fi
  if [[ "$type" == "tcp" || "$type" == "http" || "$type" == "https" ]]; then
    if confirm "是否添加健康检查" "n"; then
      if [[ "$type" == "http" || "$type" == "https" ]]; then
        hc_type="http"
        hc_path="$(ask "健康检查路径" "/")"
        echo "healthCheck.type = \"http\"" >> "$file"
        echo "healthCheck.path = \"$(toml_escape "$hc_path")\"" >> "$file"
      else
        echo "healthCheck.type = \"tcp\"" >> "$file"
      fi
      echo "healthCheck.intervalSeconds = 10" >> "$file"
      echo "healthCheck.timeoutSeconds = 3" >> "$file"
      echo "healthCheck.maxFailed = 3" >> "$file"
    fi
  fi
}

add_proxy_tcp_udp() {
  local type="$1" name="$2" file="$3" local_ip local_port remote_port
  local_ip="$(ask "本地服务 IP localIP" "127.0.0.1")"
  local_port="$(ask_port "本地服务端口 localPort" "")"
  remote_port="$(ask_port "服务端暴露端口 remotePort" "")"
  cat > "$file" <<EOF_PROXY
[[proxies]]
name = "$(toml_escape "$name")"
type = "${type}"
localIP = "$(toml_escape "$local_ip")"
localPort = ${local_port}
remotePort = ${remote_port}
EOF_PROXY
  append_common_proxy_options "$file" "$type"
}

add_proxy_http_https() {
  local type="$1" name="$2" file="$3" local_ip local_port domain_mode domains subdomain
  local locations host_rewrite http_user http_pass
  local_ip="$(ask "本地 Web 服务 IP localIP" "127.0.0.1")"
  local_port="$(ask_port "本地 Web 服务端口 localPort" "80")"
  cat > "$file" <<EOF_PROXY
[[proxies]]
name = "$(toml_escape "$name")"
type = "${type}"
localIP = "$(toml_escape "$local_ip")"
localPort = ${local_port}
EOF_PROXY

  echo "域名方式：1) customDomains 自定义域名  2) subdomain 二级域名  3) 两者都写"
  domain_mode="$(ask "请选择" "1")"
  if [[ "$domain_mode" == "1" || "$domain_mode" == "3" ]]; then
    domains="$(ask_required "customDomains，多个用英文逗号分隔" "")"
    echo "customDomains = $(toml_array_from_csv "$domains")" >> "$file"
  fi
  if [[ "$domain_mode" == "2" || "$domain_mode" == "3" ]]; then
    subdomain="$(ask_required "subdomain，例如 nas -> nas.your-frps-domain.com" "")"
    echo "subdomain = \"$(toml_escape "$subdomain")\"" >> "$file"
  fi

  # locations / hostHeaderRewrite / httpUser / httpPassword are HTTP-only fields.
  if [[ "$type" == "http" ]]; then
    locations="$(ask "URL 路由 locations，多个逗号分隔；留空不设置，例如 /api,/static" "")"
    [[ -n "$locations" ]] && echo "locations = $(toml_array_from_csv "$locations")" >> "$file"
    host_rewrite="$(ask "Host Header 重写 hostHeaderRewrite，留空不设置" "")"
    [[ -n "$host_rewrite" ]] && echo "hostHeaderRewrite = \"$(toml_escape "$host_rewrite")\"" >> "$file"

    if confirm "是否给该 HTTP 代理添加 BasicAuth" "n"; then
      http_user="$(ask_required "HTTP BasicAuth 用户名" "admin")"
      http_pass="$(ask "HTTP BasicAuth 密码，留空随机" "")"
      [[ -z "$http_pass" ]] && http_pass="$(random_secret | cut -c1-16)"
      echo "httpUser = \"$(toml_escape "$http_user")\"" >> "$file"
      echo "httpPassword = \"$(toml_escape "$http_pass")\"" >> "$file"
      ok "HTTP BasicAuth：${http_user} / ${http_pass}"
    fi
  fi

  append_common_proxy_options "$file" "$type"
}

add_proxy_stcp_xtcp_sudp() {
  local type="$1" name="$2" file="$3" local_ip local_port secret allow_users
  local_ip="$(ask "本地服务 IP localIP" "127.0.0.1")"
  local_port="$(ask_port "本地服务端口 localPort" "22")"
  secret="$(ask "secretKey，留空随机生成" "")"
  [[ -z "$secret" ]] && secret="$(random_secret)"
  allow_users="$(ask "allowUsers，留空默认同 user；允许所有 visitor 填 *" "")"

  cat > "$file" <<EOF_PROXY
[[proxies]]
name = "$(toml_escape "$name")"
type = "${type}"
secretKey = "$(toml_escape "$secret")"
localIP = "$(toml_escape "$local_ip")"
localPort = ${local_port}
EOF_PROXY
  [[ -n "$allow_users" ]] && echo "allowUsers = $(toml_array_from_csv "$allow_users")" >> "$file"
  append_common_proxy_options "$file" "$type"
  ok "secretKey：$secret"
}

add_visitor_stcp_xtcp_sudp() {
  local type="$1" name="$2" file="$3" server_name secret bind_addr bind_port
  server_name="$(ask_required "要访问的服务端代理名 serverName" "")"
  secret="$(ask_required "secretKey，需要和服务端代理一致" "")"
  bind_addr="$(ask "本机访问监听地址 bindAddr" "127.0.0.1")"
  bind_port="$(ask_port "本机访问监听端口 bindPort" "6000")"
  cat > "$file" <<EOF_VISITOR
[[visitors]]
name = "$(toml_escape "$name")"
type = "${type}"
serverName = "$(toml_escape "$server_name")"
secretKey = "$(toml_escape "$secret")"
bindAddr = "$(toml_escape "$bind_addr")"
bindPort = ${bind_port}
EOF_VISITOR
}

render_xtcp_payload() {
  local server_addr="$1" server_port="$2" proxy_name="$3" visitor_name="$4" secret="$5"
  local bind_addr="$6" bind_port="$7" keep_tunnel_open="$8" fallback="$9"
  local fallback_proxy_name="${10}" fallback_visitor_name="${11}" fallback_timeout_ms="${12}"
  cat <<EOF_XTCP_PAYLOAD
format = "install-frp-xtcp-v1"
serverAddr = "$(toml_escape "$server_addr")"
serverPort = ${server_port}
proxyName = "$(toml_escape "$proxy_name")"
visitorName = "$(toml_escape "$visitor_name")"
secretKey = "$(toml_escape "$secret")"
bindAddr = "$(toml_escape "$bind_addr")"
bindPort = ${bind_port}
keepTunnelOpen = ${keep_tunnel_open}
fallback = ${fallback}
fallbackProxyName = "$(toml_escape "$fallback_proxy_name")"
fallbackVisitorName = "$(toml_escape "$fallback_visitor_name")"
fallbackTimeoutMs = ${fallback_timeout_ms}
EOF_XTCP_PAYLOAD
}

parse_xtcp_payload_value() {
  parse_payload_value "$1" "$2"
}

write_xtcp_exposed_config() {
  local file="$1" proxy_name="$2" secret="$3" local_ip="$4" local_port="$5"
  local fallback="${6:-false}" fallback_proxy_name="${7:-}"
  mkdir -p "${file%/*}"
  cat > "$file" <<EOF_XTCP_EXPOSED
[[proxies]]
name = "$(toml_escape "$proxy_name")"
type = "xtcp"
secretKey = "$(toml_escape "$secret")"
localIP = "$(toml_escape "$local_ip")"
localPort = ${local_port}
EOF_XTCP_EXPOSED

  if [[ "$fallback" == "true" ]]; then
    cat >> "$file" <<EOF_XTCP_STCP

[[proxies]]
name = "$(toml_escape "$fallback_proxy_name")"
type = "stcp"
secretKey = "$(toml_escape "$secret")"
localIP = "$(toml_escape "$local_ip")"
localPort = ${local_port}
EOF_XTCP_STCP
  fi
  chown root:"$FRP_USER" "$file" 2>/dev/null || true
  chmod 640 "$file" 2>/dev/null || true
}

write_xtcp_visitor_config_from_payload() {
  local file="$1" payload="$2"
  local format server_name visitor_name secret bind_addr bind_port keep_tunnel_open
  local fallback fallback_proxy_name fallback_visitor_name fallback_timeout_ms
  format="$(parse_xtcp_payload_value "$payload" format)"
  [[ "$format" == "install-frp-xtcp-v1" ]] || fatal "XTCP 导入码内容格式不正确。"
  server_name="$(parse_xtcp_payload_value "$payload" proxyName)"
  visitor_name="$(parse_xtcp_payload_value "$payload" visitorName)"
  secret="$(parse_xtcp_payload_value "$payload" secretKey)"
  bind_addr="$(parse_xtcp_payload_value "$payload" bindAddr)"
  bind_port="$(parse_xtcp_payload_value "$payload" bindPort)"
  keep_tunnel_open="$(parse_xtcp_payload_value "$payload" keepTunnelOpen)"
  fallback="$(parse_xtcp_payload_value "$payload" fallback)"
  fallback_proxy_name="$(parse_xtcp_payload_value "$payload" fallbackProxyName)"
  fallback_visitor_name="$(parse_xtcp_payload_value "$payload" fallbackVisitorName)"
  fallback_timeout_ms="$(parse_xtcp_payload_value "$payload" fallbackTimeoutMs)"

  mkdir -p "${file%/*}"
  : > "$file"
  if [[ "$fallback" == "true" ]]; then
    cat >> "$file" <<EOF_XTCP_STCP_VISITOR
[[visitors]]
name = "$(toml_escape "$fallback_visitor_name")"
type = "stcp"
serverName = "$(toml_escape "$fallback_proxy_name")"
secretKey = "$(toml_escape "$secret")"
bindPort = -1

EOF_XTCP_STCP_VISITOR
  fi

  cat >> "$file" <<EOF_XTCP_VISITOR
[[visitors]]
name = "$(toml_escape "$visitor_name")"
type = "xtcp"
serverName = "$(toml_escape "$server_name")"
secretKey = "$(toml_escape "$secret")"
bindAddr = "$(toml_escape "$bind_addr")"
bindPort = ${bind_port}
keepTunnelOpen = ${keep_tunnel_open}
EOF_XTCP_VISITOR

  if [[ "$fallback" == "true" ]]; then
    cat >> "$file" <<EOF_XTCP_FALLBACK
fallbackTo = "$(toml_escape "$fallback_visitor_name")"
fallbackTimeoutMs = ${fallback_timeout_ms}
EOF_XTCP_FALLBACK
  fi

  chown root:"$FRP_USER" "$file" 2>/dev/null || true
  chmod 640 "$file" 2>/dev/null || true
}

select_frpc_split_dir_for_write() {
  local target name
  echo "写入目标：1) 默认 frpc  2) 命名 frpc 实例"
  target="$(ask "请选择" "1")"
  case "$target" in
    1|default|frpc)
      SELECTED_FRPC_CONFIG="$FRPC_CONFIG"
      SELECTED_FRPC_SPLIT_DIR="$FRPC_CONF_DIR"
      SELECTED_FRPC_SERVICE="frpc"
      ;;
    2|instance)
      name="$(ask_required "实例名" "")"
      validate_instance_name "$name" || { warn "实例名不合法：$name"; return 1; }
      SELECTED_FRPC_CONFIG="$(instance_frpc_config "$name")"
      SELECTED_FRPC_SPLIT_DIR="$(instance_frpc_conf_dir "$name")"
      SELECTED_FRPC_SERVICE="$(instance_service_name "$name")"
      ;;
    *) warn "无效选择"; return 1 ;;
  esac
  mkdir -p "$SELECTED_FRPC_SPLIT_DIR"
}

create_xtcp_exposed_and_code() {
  create_dirs_and_user
  local server_addr server_port name secret local_ip local_port bind_addr bind_port keep_open fallback
  local fallback_proxy fallback_visitor timeout passphrase payload code safe_name file
  select_frpc_split_dir_for_write || return 0
  server_addr="$(ask_required "导入端连接的 frps 地址/IP/域名" "")"
  server_port="$(ask_port "导入端连接的 frps 端口" "7000")"
  name="$(ask_required "XTCP 代理名 proxyName" "p2p_ssh")"
  secret="$(ask "secretKey，留空随机生成" "")"
  [[ -z "$secret" ]] && secret="$(random_secret)"
  local_ip="$(ask "被访问本地服务 IP localIP" "127.0.0.1")"
  local_port="$(ask_port "被访问本地服务端口 localPort" "22")"
  bind_addr="$(ask "访问端本地监听地址 bindAddr" "127.0.0.1")"
  bind_port="$(ask_port "访问端本地监听端口 bindPort" "6000")"
  keep_open="$(ask_yes_no_value "访问端是否 keepTunnelOpen" "n")"
  fallback="$(ask_yes_no_value "是否生成 STCP fallback" "Y")"
  fallback_proxy="${name}_stcp"
  fallback_visitor="${name}_stcp_fallback"
  timeout="$(ask "fallbackTimeoutMs" "200")"
  [[ "$timeout" =~ ^[0-9]+$ ]] || timeout=200

  safe_name="$(safe_filename "$name")"
  file="${SELECTED_FRPC_SPLIT_DIR}/${safe_name}.toml"
  if [[ -f "$file" ]]; then
    if confirm "配置 ${file} 已存在，是否覆盖" "n"; then
      backup_file "$file" >/dev/null || true
    else
      return 0
    fi
  fi
  write_xtcp_exposed_config "$file" "$name" "$secret" "$local_ip" "$local_port" "$fallback" "$fallback_proxy"
  verify_config "${INSTALL_DIR}/frpc" "$SELECTED_FRPC_CONFIG"

  payload="$(render_xtcp_payload "$server_addr" "$server_port" "$name" "${name}_visitor" "$secret" "$bind_addr" "$bind_port" "$keep_open" "$fallback" "$fallback_proxy" "$fallback_visitor" "$timeout")"
  passphrase="$(ask "导入码加密口令，留空随机生成" "")"
  [[ -z "$passphrase" ]] && passphrase="$(random_secret | cut -c1-20)"
  code="$(encrypt_payload_code "IFRP-XTCP-V1" "$passphrase" "$payload")"

  warn "下面的导入码和口令合在一起等同于 secretKey，请勿公开。"
  echo
  echo "========== XTCP 加密导入码 =========="
  echo "$code"
  echo "========== 解密码 =========="
  echo "$passphrase"
  echo "===================================="
}

import_xtcp_code_to_visitor() {
  create_dirs_and_user
  local code passphrase payload visitor_name safe_name file
  select_frpc_split_dir_for_write || return 0
  warn "请粘贴 XTCP 加密导入码，格式为 IFRP-XTCP-V1:..."
  code="$(ask_required "XTCP 导入码" "")"
  passphrase="$(ask_required "解密码" "")"
  payload="$(decrypt_payload_code "IFRP-XTCP-V1" "$passphrase" "$code")"
  visitor_name="$(parse_xtcp_payload_value "$payload" visitorName)"
  [[ -n "$visitor_name" ]] || fatal "导入码缺少 visitorName。"
  safe_name="$(safe_filename "$visitor_name")"
  file="${SELECTED_FRPC_SPLIT_DIR}/${safe_name}.toml"
  if [[ -f "$file" ]]; then
    if confirm "配置 ${file} 已存在，是否覆盖" "n"; then
      backup_file "$file" >/dev/null || true
    else
      return 0
    fi
  fi
  write_xtcp_visitor_config_from_payload "$file" "$payload"
  verify_config "${INSTALL_DIR}/frpc" "$SELECTED_FRPC_CONFIG"
  if systemctl list-unit-files "${SELECTED_FRPC_SERVICE}.service" >/dev/null 2>&1; then
    if confirm "是否重启 ${SELECTED_FRPC_SERVICE} 使配置生效" "Y"; then
      systemctl restart "$SELECTED_FRPC_SERVICE"
      systemctl --no-pager --full status "$SELECTED_FRPC_SERVICE" || true
    fi
  fi
  ok "已导入 XTCP 访问端配置：$file"
}

xtcp_pair_menu() {
  while true; do
    echo
    info "XTCP / STCP 加密导入码"
    cat <<'MENU_XTCP_CODE'
1) 创建被访问端 XTCP 配置并生成加密导入码
2) 粘贴加密导入码生成访问端配置
0) 返回
MENU_XTCP_CODE
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) create_xtcp_exposed_and_code; pause ;;
      2) import_xtcp_code_to_visitor; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

safe_filename() {
  local name="$1"
  printf '%s' "$name" | sed 's/[^A-Za-z0-9._-]/_/g'
}

preset_meta_get() {
  local file="$1" key="$2"
  [[ -f "$file" ]] || return 0
  awk -v want="$key" '
    /^#/ {
      line=$0
      sub(/^#[[:space:]]*/, "", line)
      pos=index(line, "=")
      if (pos == 0) next
      k=substr(line, 1, pos-1)
      v=substr(line, pos+1)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", k)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", v)
      if (k == want) {
        if (v ~ /^".*"$/) {
          sub(/^"/, "", v)
          sub(/"$/, "", v)
        }
        print v
        exit
      }
    }
  ' "$file"
}

extract_template_vars() {
  local file="$1" meta var
  meta="$(preset_meta_get "$file" "vars")"
  if [[ -n "$meta" ]]; then
    local oldifs="$IFS"
    IFS=',' read -r -a arr <<< "$meta"
    IFS="$oldifs"
    for var in "${arr[@]}"; do
      var="$(trim "$var")"
      [[ -n "$var" ]] && printf '%s\n' "$var"
    done
    return 0
  fi
  grep -oE '\$\{[A-Za-z_][A-Za-z0-9_]*\}|\{\{[A-Za-z_][A-Za-z0-9_]*\}\}' "$file" 2>/dev/null \
    | sed -E 's/^\$\{//; s/^\{\{//; s/\}$//; s/\}\}$//' \
    | awk '!seen[$0]++'
}

preset_list_files() {
  find "$PRESET_DIR" -maxdepth 1 -type f \( -name '*.tpl' -o -name '*.toml.tpl' -o -name '*.preset' \) 2>/dev/null | sort
}

choose_preset_file() {
  local files=() file idx choice title desc
  while IFS= read -r file; do files+=("$file"); done < <(preset_list_files)
  if (( ${#files[@]} == 0 )); then
    warn "还没有自定义预设。请先在预设管理里创建，目录：$PRESET_DIR"
    return 1
  fi
  echo >&2
  info "自定义预设列表"
  idx=1
  for file in "${files[@]}"; do
    title="$(preset_meta_get "$file" "name")"
    desc="$(preset_meta_get "$file" "desc")"
    [[ -n "$title" ]] || title="$(basename "$file")"
    if [[ -n "$desc" ]]; then
      printf '%s) %s - %s\n' "$idx" "$title" "$desc" >&2
    else
      printf '%s) %s\n' "$idx" "$title" >&2
    fi
    idx=$((idx+1))
  done
  echo "0) 返回" >&2
  choice="$(ask "请选择预设" "1")"
  [[ "$choice" == "0" || "$choice" =~ ^[Qq]$ ]] && return 1
  if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#files[@]} )); then
    SELECTED_PRESET_FILE="${files[$((choice-1))]}"
    return 0
  fi
  warn "无效选择。"
  return 1
}

write_rendered_frpc_config() {
  local output_file="$1" tmpfile="$2"
  mkdir -p "$FRPC_CONF_DIR"
  if [[ -f "$output_file" ]]; then
    if confirm "配置 ${output_file} 已存在，是否覆盖" "n"; then
      cp -a "$output_file" "${output_file}.bak.$(date +%Y%m%d-%H%M%S)"
    else
      return 1
    fi
  fi
  install -m 0640 "$tmpfile" "$output_file"
  chown root:"$FRP_USER" "$output_file" 2>/dev/null || true
  ok "已写入：$output_file"
  verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"
  if systemctl list-unit-files frpc.service >/dev/null 2>&1; then
    if confirm "是否重启 frpc 使配置生效" "Y"; then
      systemctl restart frpc
      systemctl --no-pager --full status frpc || true
    fi
  fi
}

render_custom_preset_to_file() {
  local preset="$1" out_name safe_name output_file tmpfile content vars=() var def value pattern
  [[ -f "$preset" ]] || fatal "预设不存在：$preset"
  echo
  info "套用自定义预设：$(preset_meta_get "$preset" "name")"
  while IFS= read -r var; do vars+=("$var"); done < <(extract_template_vars "$preset")
  content="$(cat "$preset")"

  if (( ${#vars[@]} > 0 )); then
    echo "需要填写变量：${vars[*]}"
    for var in "${vars[@]}"; do
      def="$(preset_meta_get "$preset" "default.${var}")"
      value="$(ask "${var}" "$def")"
      value="$(toml_escape "$value")"
      pattern="\${${var}}"
      content="${content//$pattern/$value}"
      pattern="{{${var}}}"
      content="${content//$pattern/$value}"
    done
  else
    warn "该预设没有声明变量，也没有检测到占位符，将原样写入。"
  fi

  # Remove preset metadata comments from rendered config, keep normal comments.
  content="$(printf '%s\n' "$content" | sed -E '/^#[[:space:]]*(frp-manager-preset-v1|name[[:space:]]*=|desc[[:space:]]*=|vars[[:space:]]*=|default\.[A-Za-z_][A-Za-z0-9_]*[[:space:]]*=)/d')"

  out_name="$(ask "生成到 frpc.d 的文件名，留空用预设文件名" "$(basename "$preset")")"
  out_name="${out_name%.tpl}"; out_name="${out_name%.toml}"; out_name="${out_name%.preset}"
  [[ -n "$(trim "$out_name")" ]] || out_name="custom"
  safe_name="$(safe_filename "$out_name")"
  output_file="${FRPC_CONF_DIR}/${safe_name}.toml"
  tmpfile="$(mktemp)"
  printf '%s\n' "$content" > "$tmpfile"

  echo
  echo "========== 渲染后的配置预览 =========="
  cat "$tmpfile"
  echo "======================================"
  if confirm "确认写入该配置" "Y"; then
    write_rendered_frpc_config "$output_file" "$tmpfile"
  else
    warn "已取消写入。"
  fi
  rm -f "$tmpfile"
}

paste_until_eof_to_file() {
  local file="$1" line
  : > "$file"
  echo "请粘贴内容，单独输入 EOF 结束："
  while IFS= read -r line; do
    [[ "$line" == "EOF" ]] && break
    printf '%s\n' "$line" >> "$file"
  done
}

create_custom_preset() {
  create_dirs_and_user
  local preset_id file title desc vars var def tmp body_method
  echo
  info "创建自定义 frpc 预设"
  cat <<'EOF_PRESET_HELP'
预设不是固定模板，而是你自己维护的 TOML 模板。
可用占位符：${name} 或 {{name}}
元数据写在 # 注释里，脚本会读取 vars/default.* 后交互询问。
EOF_PRESET_HELP
  preset_id="$(ask_required "预设文件名，例如 ssh-tcp 或 nas-http" "")"
  preset_id="$(safe_filename "$preset_id")"
  file="${PRESET_DIR}/${preset_id}.tpl"
  if [[ -f "$file" ]]; then
    if ! confirm "预设 ${file} 已存在，是否覆盖" "n"; then
      return 0
    fi
  fi
  title="$(ask "预设显示名" "$preset_id")"
  desc="$(ask "预设描述" "")"
  vars="$(ask "变量列表，英文逗号分隔，例如 name,localIP,localPort,remotePort" "name,localIP,localPort,remotePort")"

  tmp="$(mktemp)"
  {
    echo "# frp-manager-preset-v1"
    echo "# name = \"$(toml_escape "$title")\""
    [[ -n "$desc" ]] && echo "# desc = \"$(toml_escape "$desc")\""
    echo "# vars = \"$(toml_escape "$vars")\""
    local oldifs="$IFS"; IFS=',' read -r -a arr <<< "$vars"; IFS="$oldifs"
    for var in "${arr[@]}"; do
      var="$(trim "$var")"
      [[ -z "$var" ]] && continue
      def="$(ask "变量 ${var} 的默认值，留空无默认" "")"
      echo "# default.${var} = \"$(toml_escape "$def")\""
    done
    echo
  } > "$tmp"

  echo "内容输入方式：1) 粘贴完整 TOML 模板  2) 生成最小代理骨架后再编辑"
  body_method="$(ask "请选择" "1")"
  if [[ "$body_method" == "2" ]]; then
    cat >> "$tmp" <<'EOF_MINIMAL_PROXY'
[[proxies]]
name = "${name}"
type = "tcp"
localIP = "${localIP}"
localPort = ${localPort}
remotePort = ${remotePort}
EOF_MINIMAL_PROXY
  else
    paste_until_eof_to_file "${tmp}.body"
    cat "${tmp}.body" >> "$tmp"
    rm -f "${tmp}.body"
  fi

  install -m 0640 "$tmp" "$file"
  rm -f "$tmp"
  chown root:"$FRP_USER" "$file" 2>/dev/null || true
  ok "已创建预设：$file"
  echo "以后可在菜单中选择该预设，并按变量交互生成 frpc.d/*.toml。"
}

edit_custom_preset() {
  create_dirs_and_user
  local file editor
  SELECTED_PRESET_FILE=""
  choose_preset_file || return 0
  file="$SELECTED_PRESET_FILE"
  editor="${EDITOR:-}"
  if [[ -z "$editor" ]]; then
    if has_cmd nano; then editor="nano"; elif has_cmd vim; then editor="vim"; elif has_cmd vi; then editor="vi"; fi
  fi
  if [[ -n "$editor" ]]; then
    "$editor" "$file"
  else
    warn "未找到 nano/vim/vi。改用覆盖粘贴模式。"
    paste_until_eof_to_file "${file}.new"
    if confirm "是否用新内容覆盖 ${file}" "Y"; then
      cp -a "$file" "${file}.bak.$(date +%Y%m%d-%H%M%S)"
      cat "${file}.new" > "$file"
    fi
    rm -f "${file}.new"
  fi
  chmod 640 "$file" 2>/dev/null || true
  chown root:"$FRP_USER" "$file" 2>/dev/null || true
  ok "预设已保存：$file"
}

show_custom_preset() {
  local file
  SELECTED_PRESET_FILE=""
  choose_preset_file || return 0
  file="$SELECTED_PRESET_FILE"
  echo
  echo "========== $file =========="
  cat "$file"
  echo "======================================"
}

delete_custom_preset() {
  local file
  SELECTED_PRESET_FILE=""
  choose_preset_file || return 0
  file="$SELECTED_PRESET_FILE"
  if confirm "确认删除预设 ${file}" "n"; then
    rm -f "$file"
    ok "已删除：$file"
  fi
}

import_example_presets() {
  create_dirs_and_user
  local file
  warn "这里导入的是可编辑示例，不会强制你使用固定模板；导入后可以在预设管理中编辑。"

  file="${PRESET_DIR}/tcp-custom.tpl"
  if [[ ! -f "$file" ]] || confirm "覆盖示例 ${file}" "n"; then
    cat > "$file" <<'EOF_TCP_PRESET'
# frp-manager-preset-v1
# name = "TCP 自定义暴露"
# desc = "自定义本地 IP/端口和远程端口"
# vars = "name,localIP,localPort,remotePort"
# default.name = "ssh"
# default.localIP = "127.0.0.1"
# default.localPort = "22"
# default.remotePort = "6000"

[[proxies]]
name = "${name}"
type = "tcp"
localIP = "${localIP}"
localPort = ${localPort}
remotePort = ${remotePort}
EOF_TCP_PRESET
  fi

  file="${PRESET_DIR}/http-custom.tpl"
  if [[ ! -f "$file" ]] || confirm "覆盖示例 ${file}" "n"; then
    cat > "$file" <<'EOF_HTTP_PRESET'
# frp-manager-preset-v1
# name = "HTTP 自定义域名"
# desc = "自定义域名访问本地 Web 服务"
# vars = "name,localIP,localPort,domain"
# default.name = "web"
# default.localIP = "127.0.0.1"
# default.localPort = "80"
# default.domain = "www.example.com"

[[proxies]]
name = "${name}"
type = "http"
localIP = "${localIP}"
localPort = ${localPort}
customDomains = ["${domain}"]
EOF_HTTP_PRESET
  fi

  file="${PRESET_DIR}/stcp-custom.tpl"
  if [[ ! -f "$file" ]] || confirm "覆盖示例 ${file}" "n"; then
    cat > "$file" <<'EOF_STCP_PRESET'
# frp-manager-preset-v1
# name = "STCP 安全暴露"
# desc = "需要 visitor 和相同 secretKey 才能访问"
# vars = "name,localIP,localPort,secretKey"
# default.name = "secret-ssh"
# default.localIP = "127.0.0.1"
# default.localPort = "22"
# default.secretKey = "change-me"

[[proxies]]
name = "${name}"
type = "stcp"
secretKey = "${secretKey}"
localIP = "${localIP}"
localPort = ${localPort}
EOF_STCP_PRESET
  fi

  chown root:"$FRP_USER" "$PRESET_DIR"/*.tpl 2>/dev/null || true
  chmod 640 "$PRESET_DIR"/*.tpl 2>/dev/null || true
  ok "示例预设已导入到：$PRESET_DIR。你可以继续编辑它们。"
}

apply_custom_preset() {
  create_dirs_and_user
  [[ -f "$FRPC_CONFIG" ]] || warn "未检测到 $FRPC_CONFIG，建议先安装/配置 frpc。"
  local file
  SELECTED_PRESET_FILE=""
  choose_preset_file || return 0
  file="$SELECTED_PRESET_FILE"
  render_custom_preset_to_file "$file"
}

paste_raw_frpc_toml() {
  create_dirs_and_user
  local name safe_name output_file tmpfile
  name="$(ask_required "生成到 frpc.d 的文件名" "custom")"
  safe_name="$(safe_filename "$name")"
  output_file="${FRPC_CONF_DIR}/${safe_name}.toml"
  tmpfile="$(mktemp)"
  paste_until_eof_to_file "$tmpfile"
  echo
  echo "========== 即将写入的 TOML =========="
  cat "$tmpfile"
  echo "======================================"
  if confirm "确认写入" "Y"; then
    write_rendered_frpc_config "$output_file" "$tmpfile"
  else
    warn "已取消写入。"
  fi
  rm -f "$tmpfile"
}

manage_custom_presets_menu() {
  while true; do
    echo
    info "自定义 frpc 预设管理"
    echo "预设目录：$PRESET_DIR"
    cat <<'EOF_PRESET_MENU'
1) 套用自定义预设生成 frpc.d 配置
2) 创建自定义预设
3) 编辑自定义预设
4) 查看自定义预设
5) 删除自定义预设
6) 导入可编辑示例预设
7) 直接粘贴 TOML 到 frpc.d
0) 返回
EOF_PRESET_MENU
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) apply_custom_preset; pause ;;
      2) create_custom_preset; pause ;;
      3) edit_custom_preset; pause ;;
      4) show_custom_preset; pause ;;
      5) delete_custom_preset; pause ;;
      6) import_example_presets; pause ;;
      7) paste_raw_frpc_toml; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

add_proxy_manual_wizard() {
  create_dirs_and_user
  [[ -f "$FRPC_CONFIG" ]] || warn "未检测到 $FRPC_CONFIG，建议先安装/配置 frpc。"
  local type name safe_name file
  echo
  info "高级手动添加 frpc 代理/访问者配置"
  echo "支持类型：tcp udp http https stcp xtcp sudp stcp-visitor xtcp-visitor sudp-visitor"
  type="$(ask "类型" "tcp")"
  case "$type" in tcp|udp|http|https|stcp|xtcp|sudp|stcp-visitor|xtcp-visitor|sudp-visitor) ;; *) fatal "不支持的类型：$type" ;; esac
  name="$(ask_required "名称 name，必须唯一" "")"
  safe_name="$(safe_filename "$name")"
  file="${FRPC_CONF_DIR}/${safe_name}.toml"

  if [[ -f "$file" ]]; then
    if confirm "配置 ${file} 已存在，是否覆盖" "n"; then
      cp -a "$file" "${file}.bak.$(date +%Y%m%d-%H%M%S)"
    else
      return
    fi
  fi

  case "$type" in
    tcp|udp) add_proxy_tcp_udp "$type" "$name" "$file" ;;
    http|https) add_proxy_http_https "$type" "$name" "$file" ;;
    stcp|xtcp|sudp) add_proxy_stcp_xtcp_sudp "$type" "$name" "$file" ;;
    stcp-visitor) add_visitor_stcp_xtcp_sudp "stcp" "$name" "$file" ;;
    xtcp-visitor) add_visitor_stcp_xtcp_sudp "xtcp" "$name" "$file" ;;
    sudp-visitor) add_visitor_stcp_xtcp_sudp "sudp" "$name" "$file" ;;
  esac

  chown root:"$FRP_USER" "$file" 2>/dev/null || true
  chmod 640 "$file"
  ok "已写入：$file"

  verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"
  if systemctl list-unit-files frpc.service >/dev/null 2>&1; then
    if confirm "是否重启 frpc 使配置生效" "Y"; then
      systemctl restart frpc
      systemctl --no-pager --full status frpc || true
    fi
  fi
}

add_proxy_wizard() {
  while true; do
    echo
    info "添加/套用 frpc 客户端配置"
    cat <<'EOF_ADD_PROXY_MENU'
1) 套用自定义预设
2) 管理自定义预设
3) 高级手动添加代理/访问者
4) 直接粘贴 TOML 到 frpc.d
0) 返回
EOF_ADD_PROXY_MENU
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) apply_custom_preset; pause ;;
      2) manage_custom_presets_menu ;;
      3) add_proxy_manual_wizard; pause ;;
      4) paste_raw_frpc_toml; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

# ---------- management ----------
show_summary() {
  echo
  echo "安装目录：${INSTALL_DIR}"
  [[ -x "${INSTALL_DIR}/frps" ]] && echo "frps：$(frp_version_text "${INSTALL_DIR}/frps")"
  [[ -x "${INSTALL_DIR}/frpc" ]] && echo "frpc：$(frp_version_text "${INSTALL_DIR}/frpc")"
  echo "配置目录：${CONFIG_DIR}"
  echo "frps 配置：${FRPS_CONFIG}"
  echo "frpc 配置：${FRPC_CONFIG}"
  echo "frpc 拆分代理：${FRPC_CONF_DIR}"
  echo "frpc 自定义预设：${PRESET_DIR}"
  echo "日志目录：${LOG_DIR}"
  echo "脚本日志：${INSTALLER_LOG}"
  load_installer_config
  echo "GitHub 下载代理：${GH_PROXY:-直连}"
  echo "脚本配置：${INSTALLER_CONFIG}"
  echo
  if has_cmd systemctl; then
    systemctl --no-pager --full status frps 2>/dev/null || true
    systemctl --no-pager --full status frpc 2>/dev/null || true
  fi
}

export_frps_pairing_code() {
  create_dirs_and_user
  local default_port token server_addr server_port proto tls_enable pool_count dns_server user_name passphrase payload code
  default_port="$(read_toml_value "$FRPS_CONFIG" "bindPort")"
  [[ -n "$default_port" ]] || default_port="7000"
  if [[ -s "$TOKEN_FILE" ]]; then
    token="$(tr -d '[:space:]' < "$TOKEN_FILE")"
  else
    token="$(read_toml_value "$FRPS_CONFIG" "auth.token")"
  fi
  [[ -n "$token" ]] || token="$(ask_required "未找到 frps token，请输入 token" "")"

  echo
  info "导出 frps -> frpc 加密接入码"
  server_addr="$(ask_required "新客户端连接的 frps 公网地址/IP/域名" "")"
  server_port="$(ask_port "新客户端连接的 frps 端口" "$default_port")"
  echo "通信协议可选：tcp / kcp / quic / websocket / wss"
  proto="$(ask "transport.protocol" "tcp")"
  case "$proto" in tcp|kcp|quic|websocket|wss) ;; *) warn "未知协议，回退 tcp"; proto="tcp" ;; esac
  tls_enable="$(ask_yes_no_value "是否启用 frpc->frps TLS；新版默认启用，建议保留" "Y")"
  pool_count="$(ask "连接池数量 transport.poolCount" "0")"
  [[ "$pool_count" =~ ^[0-9]+$ ]] || pool_count=0
  dns_server="$(ask "新客户端自定义 DNS，留空使用系统 DNS" "")"
  user_name="$(ask "新客户端 user，留空不设置" "")"
  passphrase="$(ask "配对码加密口令，留空随机生成" "")"
  [[ -z "$passphrase" ]] && passphrase="$(random_secret | cut -c1-20)"

  payload="$(render_frpc_pairing_payload "$server_addr" "$server_port" "$token" "$proto" "$tls_enable" "$pool_count" "$dns_server" "$user_name")"
  code="$(encrypt_payload_code "IFRP-FRPC-V1" "$passphrase" "$payload")"

  warn "下面的配对码和口令合在一起等同于 frps token，请勿公开。"
  echo
  echo "========== frps -> frpc 加密接入码 =========="
  echo "$code"
  echo "========== 解密码 =========="
  echo "$passphrase"
  echo "============================================"
}

import_frps_pairing_code() {
  create_dirs_and_user
  local code passphrase payload target name config split_dir token_file log_file store_file service
  warn "请粘贴 frps 接入配对码，格式为 IFRP-FRPC-V1:..."
  code="$(ask_required "frps 接入配对码" "")"
  passphrase="$(ask_required "解密码" "")"
  payload="$(decrypt_payload_code "IFRP-FRPC-V1" "$passphrase" "$code")"

  echo "导入目标：1) 默认 frpc  2) 命名 frpc 实例"
  target="$(ask "请选择" "1")"
  case "$target" in
    1|default|frpc)
      config="$FRPC_CONFIG"
      split_dir="$FRPC_CONF_DIR"
      token_file="$TOKEN_FILE"
      log_file="${LOG_DIR}/frpc.log"
      store_file="$FRPC_STORE"
      service="frpc"
      ;;
    2|instance)
      name="$(ask_required "实例名" "")"
      validate_instance_name "$name" || { warn "实例名不合法：$name"; return 0; }
      config="$(instance_frpc_config "$name")"
      split_dir="$(instance_frpc_conf_dir "$name")"
      token_file="$(instance_token_file "$name")"
      log_file="$(instance_log_file "$name")"
      store_file="$(instance_dir "$name")/frpc-store.json"
      service="$(instance_service_name "$name")"
      write_frpc_template_service
      ;;
    *) warn "无效选择"; return 0 ;;
  esac

  if [[ -f "$config" ]]; then
    if confirm "配置 ${config} 已存在，是否覆盖" "n"; then
      backup_file "$config" >/dev/null || true
    else
      return 0
    fi
  fi

  write_frpc_config_from_pairing_payload "$config" "$split_dir" "$token_file" "$log_file" "$store_file" "$payload"
  verify_config "${INSTALL_DIR}/frpc" "$config"
  if systemctl list-unit-files "${service}.service" >/dev/null 2>&1; then
    if confirm "是否重启 ${service} 使配置生效" "Y"; then
      systemctl restart "$service"
      systemctl --no-pager --full status "$service" || true
    fi
  fi
  ok "已导入 frps 接入配置：$config"
}

manage_named_frpc_service_action() {
  local name action service
  name="$(ask_required "实例名" "")"
  validate_instance_name "$name" || { warn "实例名不合法：$name"; return 0; }
  service="$(instance_service_name "$name")"
  echo "操作：1) status  2) start  3) stop  4) restart  5) logs -f  6) enable  7) disable"
  action="$(ask "请选择" "1")"
  case "$action" in
    1|status) systemctl --no-pager --full status "$service" || true ;;
    2|start) systemctl start "$service"; systemctl --no-pager --full status "$service" || true ;;
    3|stop) systemctl stop "$service" ;;
    4|restart) systemctl restart "$service"; systemctl --no-pager --full status "$service" || true ;;
    5|logs) journalctl -u "$service" -n 100 -f ;;
    6|enable) systemctl enable "$service" ;;
    7|disable) systemctl disable "$service" ;;
    *) warn "无效选择" ;;
  esac
}

delete_named_frpc_instance() {
  local name dir service
  name="$(ask_required "要删除的实例名" "")"
  validate_instance_name "$name" || { warn "实例名不合法：$name"; return 0; }
  dir="$(instance_dir "$name")"
  service="$(instance_service_name "$name")"
  [[ -d "$dir" ]] || { warn "实例目录不存在：$dir"; return 0; }
  warn "即将删除实例 ${name}，目录：$dir"
  if confirm "确认继续" "n"; then
    systemctl stop "$service" 2>/dev/null || true
    systemctl disable "$service" 2>/dev/null || true
    rm -rf "$dir"
    ok "已删除实例：$name"
  fi
}

manage_frpc_instances_menu() {
  while true; do
    echo
    info "frpc 命名实例管理"
    echo "实例目录：$FRPC_CLIENTS_DIR"
    cat <<'MENU_FRPC_INSTANCES'
1) 列出命名 frpc 实例
2) 新建/重配命名 frpc 实例
3) 管理命名实例 systemd 服务
4) 校验命名实例配置
5) 删除命名实例
0) 返回
MENU_FRPC_INSTANCES
    local choice name config
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1|list) list_frpc_instances || true; pause ;;
      2|create|configure) configure_named_frpc_instance; pause ;;
      3|service) manage_named_frpc_service_action; pause ;;
      4|verify)
        name="$(ask_required "实例名" "")"
        validate_instance_name "$name" || { warn "实例名不合法：$name"; pause; continue; }
        config="$(instance_frpc_config "$name")"
        verify_config "${INSTALL_DIR}/frpc" "$config"
        pause
        ;;
      5|delete|remove) delete_named_frpc_instance; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

frps_management_menu() {
  while true; do
    echo
    info "frps 服务端管理"
    render_component_status "frps" "${INSTALL_DIR}/frps" "$FRPS_CONFIG" "frps"
    echo
    cat <<'MENU_FRPS'
1) 安装/更新 frps 服务端
2) 管理 frps systemd 服务
3) 校验 frps 配置
4) 查看 frps 配置
5) 查看 frps 日志
6) 导出 frpc 加密接入码
0) 返回
MENU_FRPS
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) install_frps_flow; pause ;;
      2) manage_single_service_menu frps; pause ;;
      3) verify_config "${INSTALL_DIR}/frps" "$FRPS_CONFIG"; pause ;;
      4) show_config_file "$FRPS_CONFIG" "frps 主配置" "true"; pause ;;
      5) show_service_log frps "200" "false"; pause ;;
      6) export_frps_pairing_code; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

frpc_management_menu() {
  while true; do
    echo
    info "frpc 客户端管理"
    render_component_status "frpc" "${INSTALL_DIR}/frpc" "$FRPC_CONFIG" "frpc"
    echo
    cat <<'MENU_FRPC'
1) 安装/更新默认 frpc 客户端
2) 管理命名 frpc 实例
3) 导入 frps 加密接入码
4) 添加/套用默认 frpc 代理配置
5) XTCP / STCP 加密导入码
6) 管理默认 frpc systemd 服务
7) 校验默认 frpc 配置
8) 查看默认 frpc 配置
9) 查看默认 frpc 日志
0) 返回
MENU_FRPC
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) install_frpc_flow; pause ;;
      2) manage_frpc_instances_menu ;;
      3) import_frps_pairing_code; pause ;;
      4) add_proxy_wizard; pause ;;
      5) xtcp_pair_menu ;;
      6) manage_single_service_menu frpc; pause ;;
      7) verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"; pause ;;
      8) show_config_file "$FRPC_CONFIG" "frpc 默认主配置" "true"; show_frpc_split_configs "true"; pause ;;
      9) show_service_log frpc "200" "false"; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

tools_menu() {
  while true; do
    echo
    info "工具/维护"
    cat <<'MENU_TOOLS'
1) 仅安装/更新 frp 二进制文件
2) 校验全部配置
3) 查看安装摘要
4) 配置 GitHub 下载代理
5) 卸载 frp
0) 返回
MENU_TOOLS
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) install_or_update_binaries; pause ;;
      2) verify_all_configs; pause ;;
      3) show_summary; pause ;;
      4) configure_github_proxy; pause ;;
      5) uninstall_frp; pause ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

manage_single_service_menu() {
  local svc="$1" action
  echo "操作：1) status  2) start  3) stop  4) restart  5) logs -f  6) enable  7) disable"
  action="$(ask "请选择" "1")"
  case "$action" in
    1|status) systemctl --no-pager --full status "$svc" || true ;;
    2|start) systemctl start "$svc"; systemctl --no-pager --full status "$svc" || true ;;
    3|stop) systemctl stop "$svc" ;;
    4|restart) systemctl restart "$svc"; systemctl --no-pager --full status "$svc" || true ;;
    5|logs) journalctl -u "$svc" -n 100 -f ;;
    6|enable) systemctl enable "$svc" ;;
    7|disable) systemctl disable "$svc" ;;
    *) warn "无效选择" ;;
  esac
}

verify_all_configs() {
  local checked=0

  if [[ -x "${INSTALL_DIR}/frps" && -f "$FRPS_CONFIG" ]]; then
    verify_config "${INSTALL_DIR}/frps" "$FRPS_CONFIG"
    checked=1
  else
    warn "跳过 frps：未同时检测到 ${INSTALL_DIR}/frps 和 $FRPS_CONFIG。"
  fi

  if [[ -x "${INSTALL_DIR}/frpc" && -f "$FRPC_CONFIG" ]]; then
    verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"
    checked=1
  else
    warn "跳过 frpc：未同时检测到 ${INSTALL_DIR}/frpc 和 $FRPC_CONFIG。"
  fi

  if (( checked == 0 )); then
    warn "没有可校验的 frp 配置。"
  else
    ok "配置校验完成。"
  fi
}

redact_config_stream() {
  sed -E \
    -e 's#(auth\.token[[:space:]]*=[[:space:]]*").*(")#\1******\2#g' \
    -e 's#(token[[:space:]]*=[[:space:]]*").*(")#\1******\2#g' \
    -e 's#(secretKey[[:space:]]*=[[:space:]]*").*(")#\1******\2#g' \
    -e 's#(webServer\.password[[:space:]]*=[[:space:]]*").*(")#\1******\2#g' \
    -e 's#(httpPassword[[:space:]]*=[[:space:]]*").*(")#\1******\2#g' \
    -e 's#(password[[:space:]]*=[[:space:]]*").*(")#\1******\2#g' \
    -e 's#(GH_PROXY=).+#\1******#g'
}

show_config_file() {
  local file="$1" title="$2" reveal="$3"
  echo
  echo "========== ${title} =========="
  if [[ ! -f "$file" ]]; then
    warn "文件不存在：$file"
    return 0
  fi
  echo "路径：$file"
  echo "----------------------------------------"
  if [[ "$reveal" == "true" ]]; then
    nl -ba "$file"
  else
    redact_config_stream < "$file" | nl -ba
  fi
}

show_token_file() {
  local reveal="$1"
  echo
  echo "========== 鉴权 Token 文件 =========="
  if [[ ! -f "$TOKEN_FILE" ]]; then
    warn "文件不存在：$TOKEN_FILE"
    return 0
  fi
  echo "路径：$TOKEN_FILE"
  echo "----------------------------------------"
  if [[ "$reveal" == "true" ]]; then
    nl -ba "$TOKEN_FILE"
  else
    printf '     1	******
'
  fi
}

show_frpc_split_configs() {
  local reveal="$1" files=() f
  echo
  echo "========== frpc 拆分代理配置 =========="
  echo "目录：$FRPC_CONF_DIR"
  if [[ ! -d "$FRPC_CONF_DIR" ]]; then
    warn "目录不存在：$FRPC_CONF_DIR"
    return 0
  fi
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$FRPC_CONF_DIR" -maxdepth 1 -type f -name '*.toml' -print0 2>/dev/null | sort -z)
  if (( ${#files[@]} == 0 )); then
    warn "没有找到拆分代理配置：${FRPC_CONF_DIR}/*.toml"
    return 0
  fi
  for f in "${files[@]}"; do
    show_config_file "$f" "$(basename "$f")" "$reveal"
  done
}

show_current_configs() {
  local choice reveal="true"
  echo
  info "查看当前配置"
  warn "当前配置会直接显示 token / password / secretKey / GH_PROXY 等明文，请勿公开截图或粘贴。"
  cat <<'MENU_CONFIG'
1) 查看 frps.toml
2) 查看 frpc.toml
3) 查看 frpc.d 拆分代理配置
4) 查看 token / installer.env
5) 查看全部配置
0) 返回
MENU_CONFIG
  choice="$(ask "请选择" "5")"
  case "$choice" in
    1|frps) show_config_file "$FRPS_CONFIG" "frps 主配置" "$reveal" ;;
    2|frpc) show_config_file "$FRPC_CONFIG" "frpc 主配置" "$reveal" ;;
    3|frpc.d|proxy|proxies) show_frpc_split_configs "$reveal" ;;
    4|token|installer) show_token_file "$reveal"; show_config_file "$INSTALLER_CONFIG" "脚本配置 installer.env" "$reveal" ;;
    5|all|全部) show_config_file "$FRPS_CONFIG" "frps 主配置" "$reveal"; show_config_file "$FRPC_CONFIG" "frpc 主配置" "$reveal"; show_frpc_split_configs "$reveal"; show_token_file "$reveal"; show_config_file "$INSTALLER_CONFIG" "脚本配置 installer.env" "$reveal" ;;
    0|q|Q) return 0 ;;
    *) warn "无效选择" ;;
  esac
}

choose_editor() {
  local editor="${EDITOR:-}"
  if [[ -n "$editor" ]] && command -v "$editor" >/dev/null 2>&1; then
    printf '%s' "$editor"
    return 0
  fi
  if has_cmd nano; then
    printf 'nano'
  elif has_cmd vim; then
    printf 'vim'
  elif has_cmd vi; then
    printf 'vi'
  else
    return 1
  fi
}

backup_file() {
  local file="$1" backup
  [[ -f "$file" ]] || return 1
  backup="${file}.bak.$(date +%Y%m%d-%H%M%S)"
  cp -a "$file" "$backup"
  printf '%s' "$backup"
}

edit_config_file() {
  local file="$1" title="$2" bin="${3:-}" service="${4:-}" editor backup tmp
  echo
  info "编辑 ${title}"
  echo "路径：$file"
  mkdir -p "${file%/*}"
  if [[ ! -f "$file" ]]; then
    if confirm "文件不存在，是否创建" "Y"; then
      : > "$file"
    else
      return 0
    fi
  fi

  backup="$(backup_file "$file" || true)"
  [[ -n "$backup" ]] && ok "已备份：$backup"

  if editor="$(choose_editor)"; then
    "$editor" "$file"
  else
    warn "未找到 nano/vim/vi，改用粘贴覆盖模式。"
    tmp="$(mktemp)"
    paste_until_eof_to_file "$tmp"
    if confirm "是否用粘贴内容覆盖 ${file}" "Y"; then
      cp "$tmp" "$file"
    fi
    rm -f "$tmp"
  fi

  chown root:"$FRP_USER" "$file" 2>/dev/null || true
  chmod 640 "$file" 2>/dev/null || true

  if [[ -n "$bin" ]]; then
    if ! verify_config "$bin" "$file"; then
      warn "配置校验失败：$file"
      if [[ -n "$backup" ]] && confirm "是否恢复备份" "Y"; then
        cp -a "$backup" "$file"
        ok "已恢复：$backup"
      fi
      return 1
    fi
  fi

  if [[ -n "$service" ]] && systemctl list-unit-files "${service}.service" >/dev/null 2>&1; then
    if confirm "是否重启 ${service} 使配置生效" "Y"; then
      systemctl restart "$service"
      systemctl --no-pager --full status "$service" || true
    fi
  fi
}

choose_frpc_split_config() {
  local dir="${1:-$FRPC_CONF_DIR}" files=() f idx choice
  SELECTED_CONFIG_FILE=""
  [[ -d "$dir" ]] || { warn "目录不存在：$dir"; return 1; }
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$dir" -maxdepth 1 -type f -name '*.toml' -print0 2>/dev/null | sort -z)
  if (( ${#files[@]} == 0 )); then
    warn "没有找到配置：${dir}/*.toml"
    return 1
  fi
  echo
  info "选择 frpc 拆分配置"
  idx=1
  for f in "${files[@]}"; do
    printf '%s) %s\n' "$idx" "$(basename "$f")"
    idx=$((idx+1))
  done
  echo "0) 返回"
  choice="$(ask "请选择" "1")"
  [[ "$choice" == "0" || "$choice" =~ ^[Qq]$ ]] && return 1
  if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#files[@]} )); then
    SELECTED_CONFIG_FILE="${files[$((choice-1))]}"
    return 0
  fi
  warn "无效选择。"
  return 1
}

config_management_menu() {
  while true; do
    echo
    info "配置管理"
    cat <<'MENU_CONFIG_MANAGE'
1) 编辑 frps 主配置
2) 编辑默认 frpc 主配置
3) 编辑默认 frpc.d 代理配置
4) 编辑命名 frpc 实例主配置
5) 编辑命名 frpc 实例代理配置
0) 返回
MENU_CONFIG_MANAGE
    local choice name config dir
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1|frps) edit_config_file "$FRPS_CONFIG" "frps 主配置" "${INSTALL_DIR}/frps" "frps"; pause ;;
      2|frpc) edit_config_file "$FRPC_CONFIG" "默认 frpc 主配置" "${INSTALL_DIR}/frpc" "frpc"; pause ;;
      3|frpc.d)
        choose_frpc_split_config "$FRPC_CONF_DIR" || { pause; continue; }
        edit_config_file "$SELECTED_CONFIG_FILE" "默认 frpc 代理配置" "${INSTALL_DIR}/frpc" "frpc"
        pause
        ;;
      4|instance-main)
        name="$(ask_required "实例名" "")"
        validate_instance_name "$name" || { warn "实例名不合法：$name"; pause; continue; }
        config="$(instance_frpc_config "$name")"
        edit_config_file "$config" "frpc 实例 ${name} 主配置" "${INSTALL_DIR}/frpc" "$(instance_service_name "$name")"
        pause
        ;;
      5|instance-proxy)
        name="$(ask_required "实例名" "")"
        validate_instance_name "$name" || { warn "实例名不合法：$name"; pause; continue; }
        dir="$(instance_frpc_conf_dir "$name")"
        choose_frpc_split_config "$dir" || { pause; continue; }
        edit_config_file "$SELECTED_CONFIG_FILE" "frpc 实例 ${name} 代理配置" "${INSTALL_DIR}/frpc" "$(instance_service_name "$name")"
        pause
        ;;
      0|q|Q) return 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

show_log_file() {
  local file="$1" title="$2" lines="${3:-200}" follow="${4:-false}"
  echo
  echo "========== ${title} =========="
  echo "路径：$file"
  echo "----------------------------------------"
  if [[ ! -f "$file" ]]; then
    warn "日志文件不存在：$file"
    warn "如果刚启用文件日志，请先重启对应服务；如果没有连接/报错，日志也可能暂时为空。"
    return 0
  fi
  if [[ ! -s "$file" ]]; then
    warn "日志文件存在但为空：$file"
    warn "frp 通常在启动、客户端连接、代理访问、错误发生时写日志；没有事件时不会持续刷屏。"
  fi
  if [[ "$follow" == "true" ]]; then
    tail -n "$lines" -F "$file" || true
  else
    tail -n "$lines" "$file" || true
  fi
}

show_journal_log() {
  local service="$1" lines="${2:-200}" follow="${3:-false}" file=""
  case "$service" in
    frps) file="${LOG_DIR}/frps.log" ;;
    frpc) file="${LOG_DIR}/frpc.log" ;;
  esac
  echo
  echo "========== ${service} systemd 日志 =========="
  echo "----------------------------------------"
  if [[ -n "$file" ]]; then
    warn "当前脚本默认把 ${service} 业务日志写到文件：${file}；systemd 日志通常只显示服务启动/停止。"
  fi
  if ! has_cmd journalctl; then
    warn "当前系统没有 journalctl。"
    return 0
  fi
  if [[ "$follow" == "true" ]]; then
    journalctl -u "$service" -n "$lines" -f --no-pager || true
  else
    journalctl -u "$service" -n "$lines" --no-pager || true
  fi
}

show_service_log() {
  local service="$1" lines="${2:-200}" follow="${3:-false}" file="" conf=""
  case "$service" in
    frps) file="${LOG_DIR}/frps.log"; conf="$FRPS_CONFIG" ;;
    frpc) file="${LOG_DIR}/frpc.log"; conf="$FRPC_CONFIG" ;;
    *) warn "未知服务：$service"; return 0 ;;
  esac

  echo
  info "查看 ${service} 综合日志"
  if [[ -f "$conf" ]]; then
    local log_to
    log_to="$(grep -E '^[[:space:]]*log\.to[[:space:]]*=' "$conf" | tail -n1 || true)"
    if [[ -n "$log_to" ]]; then
      echo "配置：${log_to}"
    else
      warn "${conf} 里没有 log.to，建议选择日志菜单里的“一键修复/启用文件日志”。"
    fi
  else
    warn "配置文件不存在：$conf"
  fi

  if [[ -f "$file" ]]; then
    show_log_file "$file" "${service} 文件日志" "$lines" "$follow"
  else
    warn "未找到 ${service} 文件日志：$file"
    warn "下面显示 systemd 日志；如果只看到 Started/Stopped，说明 frp 没有向 stdout 输出业务日志。"
    show_journal_log "$service" "$lines" "$follow"
  fi
}

patch_log_config_file() {
  local conf="$1" file="$2" title="$3" changed=0
  [[ -f "$conf" ]] || { warn "配置文件不存在：$conf"; return 0; }
  cp -a "$conf" "${conf}.bak.$(date +%Y%m%d-%H%M%S)"

  if grep -Eq '^[[:space:]]*log\.to[[:space:]]*=' "$conf"; then
    sed -i -E "s#^[[:space:]]*log\.to[[:space:]]*=.*#log.to = \"${file}\"#" "$conf"
  else
    printf '\n# Logs.\nlog.to = "%s"\n' "$file" >> "$conf"
  fi

  if grep -Eq '^[[:space:]]*log\.level[[:space:]]*=' "$conf"; then
    sed -i -E 's#^[[:space:]]*log\.level[[:space:]]*=.*#log.level = "info"#' "$conf"
  else
    printf 'log.level = "info"\n' >> "$conf"
  fi

  if grep -Eq '^[[:space:]]*log\.maxDays[[:space:]]*=' "$conf"; then
    sed -i -E 's#^[[:space:]]*log\.maxDays[[:space:]]*=.*#log.maxDays = 7#' "$conf"
  else
    printf 'log.maxDays = 7\n' >> "$conf"
  fi

  if grep -Eq '^[[:space:]]*log\.disablePrintColor[[:space:]]*=' "$conf"; then
    sed -i -E 's#^[[:space:]]*log\.disablePrintColor[[:space:]]*=.*#log.disablePrintColor = true#' "$conf"
  else
    printf 'log.disablePrintColor = true\n' >> "$conf"
  fi

  chown root:"$FRP_USER" "$conf" 2>/dev/null || true
  chmod 640 "$conf" 2>/dev/null || true
  ok "已修复 ${title} 日志配置：$conf -> $file"
}

fix_log_config_menu() {
  local choice restart_services=()
  echo
  info "一键修复/启用文件日志"
  cat <<'MENU_FIX_LOGS'
1) 修复 frps 文件日志配置
2) 修复 frpc 文件日志配置
3) 两个都修复
0) 返回
MENU_FIX_LOGS
  choice="$(ask "请选择" "3")"
  mkdir -p "$LOG_DIR"
  if id "$FRP_USER" >/dev/null 2>&1; then
    chown -R "$FRP_USER":"$FRP_USER" "$LOG_DIR" 2>/dev/null || true
  fi
  chmod 750 "$LOG_DIR" 2>/dev/null || true

  case "$choice" in
    1|frps)
      patch_log_config_file "$FRPS_CONFIG" "${LOG_DIR}/frps.log" "frps"
      touch "${LOG_DIR}/frps.log" 2>/dev/null || true
      chown "$FRP_USER":"$FRP_USER" "${LOG_DIR}/frps.log" 2>/dev/null || true
      verify_config "${INSTALL_DIR}/frps" "$FRPS_CONFIG"
      restart_services+=(frps)
      ;;
    2|frpc)
      patch_log_config_file "$FRPC_CONFIG" "${LOG_DIR}/frpc.log" "frpc"
      touch "${LOG_DIR}/frpc.log" 2>/dev/null || true
      chown "$FRP_USER":"$FRP_USER" "${LOG_DIR}/frpc.log" 2>/dev/null || true
      verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"
      restart_services+=(frpc)
      ;;
    3|all|全部)
      patch_log_config_file "$FRPS_CONFIG" "${LOG_DIR}/frps.log" "frps"
      patch_log_config_file "$FRPC_CONFIG" "${LOG_DIR}/frpc.log" "frpc"
      touch "${LOG_DIR}/frps.log" "${LOG_DIR}/frpc.log" 2>/dev/null || true
      chown "$FRP_USER":"$FRP_USER" "${LOG_DIR}/frps.log" "${LOG_DIR}/frpc.log" 2>/dev/null || true
      verify_config "${INSTALL_DIR}/frps" "$FRPS_CONFIG"
      verify_config "${INSTALL_DIR}/frpc" "$FRPC_CONFIG"
      restart_services+=(frps frpc)
      ;;
    0|q|Q) return 0 ;;
    *) warn "无效选择"; return 0 ;;
  esac

  if confirm "是否现在重启相关服务让日志配置生效" "Y"; then
    local svc
    for svc in "${restart_services[@]}"; do
      if systemctl list-unit-files "${svc}.service" >/dev/null 2>&1; then
        systemctl restart "$svc" || warn "重启 ${svc} 失败，请查看 systemd 状态。"
      fi
    done
  else
    warn "未重启服务，新的 log.to 要等下次重启后生效。"
  fi
}

show_logs_menu() {
  local choice lines follow
  echo
  info "查看日志"
  lines="$(ask_port "显示最近多少行" "200")"
  if confirm "是否实时跟踪日志" "n"; then
    follow="true"
    warn "实时跟踪模式下按 Ctrl+C 返回/退出。"
  else
    follow="false"
  fi
  cat <<'MENU_LOGS'
1) frps 综合日志（推荐）
2) frpc 综合日志（推荐）
3) frps systemd 日志
4) frpc systemd 日志
5) frps 文件日志 /var/log/frp/frps.log
6) frpc 文件日志 /var/log/frp/frpc.log
7) 脚本安装/管理日志 /var/log/frp/installer.log
8) 全部最近日志
9) 一键修复/启用文件日志
0) 返回
MENU_LOGS
  choice="$(ask "请选择" "1")"
  case "$choice" in
    1|frps|frps-all) show_service_log frps "$lines" "$follow" ;;
    2|frpc|frpc-all) show_service_log frpc "$lines" "$follow" ;;
    3|frps-journal) show_journal_log frps "$lines" "$follow" ;;
    4|frpc-journal) show_journal_log frpc "$lines" "$follow" ;;
    5|frps-file) show_log_file "${LOG_DIR}/frps.log" "frps 文件日志" "$lines" "$follow" ;;
    6|frpc-file) show_log_file "${LOG_DIR}/frpc.log" "frpc 文件日志" "$lines" "$follow" ;;
    7|installer) show_log_file "$INSTALLER_LOG" "脚本安装/管理日志" "$lines" "$follow" ;;
    8|all|全部)
      if [[ "$follow" == "true" ]]; then
        warn "全部日志不支持同时实时跟踪，将显示最近 ${lines} 行。"
      fi
      show_service_log frps "$lines" "false"
      show_service_log frpc "$lines" "false"
      show_journal_log frps "$lines" "false"
      show_journal_log frpc "$lines" "false"
      show_log_file "$INSTALLER_LOG" "脚本安装/管理日志" "$lines" "false"
      ;;
    9|fix|repair) fix_log_config_menu ;;
    0|q|Q) return 0 ;;
    *) warn "无效选择" ;;
  esac
}

uninstall_frp() {
  warn "即将卸载 frp。"
  if ! confirm "确认继续" "n"; then return; fi
  systemctl stop frps frpc 2>/dev/null || true
  systemctl disable frps frpc 2>/dev/null || true
  rm -f /etc/systemd/system/frps.service /etc/systemd/system/frpc.service
  systemctl daemon-reload 2>/dev/null || true
  rm -f "${INSTALL_DIR}/frps" "${INSTALL_DIR}/frpc"
  if confirm "是否删除配置目录 ${CONFIG_DIR}" "n"; then
    rm -rf "$CONFIG_DIR"
  fi
  if confirm "是否删除日志目录 ${LOG_DIR}" "n"; then
    rm -rf "$LOG_DIR"
  fi
  ok "卸载完成。"
}

render_main_menu() {
  cat <<'MENU_MAIN'
1) 服务端
2) 客户端
3) 配置
4) 日志
5) 工具
0) 退出
MENU_MAIN
}

main_menu() {
  need_root
  load_installer_config
  while true; do
    print_banner
    render_main_menu
    local choice
    choice="$(ask "请选择" "1")"
    case "$choice" in
      1) frps_management_menu ;;
      2) frpc_management_menu ;;
      3) config_management_menu ;;
      4) show_logs_menu; pause ;;
      5) tools_menu ;;
      0|q|Q) exit 0 ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

if [[ "${FRP_LIB_ONLY:-0}" != "1" ]]; then
  main_menu "$@"
fi
